### DISCUSSION TITLE
Could not find type with alias "Query

### DISCUSSION THREAD

**Discussion by Sivaranjani-45** [overblog/GraphQLBundle#1188] [General]
While creating simple project (Symfony 7.1) with sample query and resolver, Got an error "Could not find type with alias "Query". Did you forget to define it?"

config/packages/overblog_graphql.yaml
```
overblog_graphql:
    definitions:
        schema:
            query: Query
        mappings:
            auto_discover:
                bundles: true
                root_dir: true
```

config/graphql/type/Query.types.yaml
```
Query:
  type: object
  config:
    fields:
      users:
        type: "[User]"
        resolve: "@=resolver('App\\GraphQL\\Resolver\\UserResolver::resolve')"
```

config/graphql/type/User.types.yaml
```
User:
  type: object
  config:
    fields:
      id:
        type: "Int!"
      name:
        type: "String!"
      petNname:
        type: "String"
      age:
        type: "Int!"
```

config/routes/graphql.yaml
```
overblog_graphql_endpoint:
  path: /graphql
  controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
  methods: [POST]

overblog_graphql_batch:
  path: /graphql/batch
  controller: Overblog\GraphQLBundle\Controller\GraphController::batchEndpointAction
  methods: [POST]
```

App/GraphQL/Resolver/UserResolver
```
class UserResolver
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function resolve(): array
    {
        return $this->entityManager->getRepository(User::class)->findAll();
    }
}
```
