### ISSUE TITLE
Issue inside of `InputValidator::buildValidationTree()` for simple input fields

### ISSUE THREAD

**Issue by ktrzos** [overblog/GraphQLBundle#1004]
Hi.

After upgrading dependency to 0.14, I'm getting this error:

> Cannot use object of type Closure as array

After analyzing the issue, I found one problem. I have this schema:

```yaml
MyMutation:
  type: object
  config:
    fields:
      edit:
        type: "MyResource!"
        resolve: "@=mutation('DoEdit', args, args.id)"
        access: '@=hasResourceEditAccess(args["id"])'
        args:
          id:
            type: "ResourceScalar!"
          input:
            type: "ResourceDataInput!"
            validation: cascade
```

with `ResourceDataInput` looking like this:

```yaml
ResourceDataInput:
  type: input-object
  config:
    fields:
      title:
        type: "String!"
        validation:
          - NotBlank: ~
          - Length: { min: 2, max: 100 }
      description:
        type: "String!"
        validation:
          - Length: { max: 200 }
      access:
        type: "ResourceAccessEnum!"
```

With above, when entering with xdebug into `InputValidator::buildValidationTree()`
![image](https://user-images.githubusercontent.com/14212721/166141059-af6296c2-7f7a-4bef-a0b5-22e887537f43.png)

I'm seeing this inside of `$fields` variable:

![image](https://user-images.githubusercontent.com/14212721/166141048-a63d49fc-ce2e-43b6-a326-671278275baf.png)

The issue is that `$fields['access']` is a Closure, and not an array. When `$arg['name'] ?? $name` executes, mentioned error occur. But when I'm changing the input schema definition of that field onto this one:

```yaml
      access:
        type: "ResourceAccessEnum!"
        validation: ~
```

then `$fields['access']` is an array as it should.

What could be the issue?
