### ISSUE TITLE
BC break when multiple arguments passed to Mutation/Query resolvers

### ISSUE THREAD

**Issue by vbartusevicius** [overblog/GraphQLBundle#1031]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | v0.14.0

When the mutation resolver has multiple arguments, they are combined into a single array.

Mutation definition:
```yaml
MutateSomething:
    argsBuilder: 'ContextArgs'
    args: { input: { type: 'SomeInput!' } }
    type: 'SomeResponse'
    resolve: '@=mutation("App\\GraphQL\\Mutation\\SomeMutation", [args, context])'
```

Mutation itself:
```php
class SomeMutation
{
    public function __invoke(ArgumentInterface $args, ArrayObject $context): array
    {
        // ...
    }
}
```
In the example above the `SomeMutation::__invoke` will NOT receive `$args` and `$context` variables, instead they will be combined into a single array, thus a single argument will be passed to `__invoke`.

It looks like the issue is in the auto-generated types:

```php
'MutateSomething' => [
    'type' => fn() => $services->getType('SomeResponse'),
    'resolve' => function ($value, $args, $context, $info) use ($services) {
        return $services->mutation("App\\GraphQL\\Mutation\\SomeMutation", [0 => $args, 1 => $context]);
    },
    'args' => [
        // ...
    ],
],
```
If this gets updated to `...[0 => $args, 1 => $context]`, then everything works fine.

Strangely enough, I see that argument unpacking is added to auto-generated queries, but not to mutations.
