### ISSUE TITLE
EntityExists validation / id exists in a table

### ISSUE THREAD

**Issue by drmax24** [overblog/GraphQLBundle#1056]
https://github.com/overblog/GraphQLBundle/issues/453

In the following post validation EntityExists was mentioned:
```
Mutation:
    type: object
    config:
        fields:
            createUser:
                type: "String"
                resolve: "@=mut('createUser', [args, validator])"
                args:
                    groups:
                        type: "[String]"
                    userId:
                        type: Int!
                        validation:
                            - EntityExists: App\Entity\User
```

I need to write a validation to check if id argument is present in a database table. Is it possible to do it right now?

If i try the above example I have an error:
Constraint class 'Symfony\Component\Validator\Constraints\EntityExists' doesn't exist.
