### ISSUE TITLE
Symfony AccessControl on Batching endpoint

### ISSUE THREAD

**Issue by jonasled** [overblog/GraphQLBundle#1059]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | v0.15.0

Hi, I have a symfony project with the security component and the graphQLBundle. For the single query endpoint everything is working fine, but with the batching endpoint the role check isn't working. Below is my configuration.

Query.types.yaml:
```yaml
Query:
  type: object
  config:
    description: "Sprint Board API Query"
    fields:
      items:
        type: "[Item]"
        description: "Returns a list of items, matching the given filters. All filters are combined with an AND operator."
        access: "@=hasRole('ROLE_ADMIN')"
        resolve: '@=resolver("getItems", [args])'
        args:
          team:
            type: "String"
            description: "The team to filter by"
            defaultValue: null
```

graphql.yaml:
```yaml
overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
    batching_method: "apollo"
```

security.yaml:
```yaml
security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    main:
      id: App\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      custom_authenticators:
        - App\Security\SessionAuthenticator
  access_control:
    # This was only added for testing, but this is also not working
    - { path: ^/api/graphql/batch, roles: ROLE_USER }
    - { roles: PUBLIC_ACCESS }
```
![batch_endpoint](https://user-images.githubusercontent.com/46790650/193027789-8c202077-8eae-4798-8ac6-fb94d6ac2562.png)
![profiler](https://user-images.githubusercontent.com/46790650/193027964-ed911f8b-e5ec-4cf3-91ad-c645f289b7b3.png)
