### ISSUE TITLE
No example of auto wiring in attributed classes

### ISSUE THREAD

**Issue by rusted-love** [overblog/GraphQLBundle#1103]
Consider following example
```#[Provider]
class TestProvider implements QueryInterface
{
    #[Query(name: 'ssss')]
    public function getSomething(int $amount, RequestService $requestService, bool $yes = true): string
    {
        return 'Hello world!'.$amount.' '.($yes ? '+' : '-').$requestService->getCurrentClientIp();
    }

    #[Mutation(name: 'ssm')]
    public function doSom(int $amount, bool $yes = true): string
    {
        return 'Hello mut!'.$amount.' '.($yes ? '+' : '-');
    }
}
```

```
overblog_graphql:
  security:
    enable_introspection: true
  definitions:
    schema:
      query: RootQuery
      mutation: RootMutation
      # the name of extra types that can not be detected
      # by graphql-php during static schema analysis.
      # These types names should be explicitly declare here
      types: [ ]
    mappings:
      types:
        - type: attribute
          dir: "%kernel.project_dir%/src/GraphQL"
          suffix: ~

```

Im trying to inject `RequestService $requestService` into `ssss` query resolver.

First issue is that when I remove `RequestService $requestService` argument I get error saying `The "App\GraphQL\TestProvider" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.`

Resolved in RootQueryType in `cache` directory looks like following:
```
'resolve' => function ($value, $args, $context, $info) use ($services) {
        return $services->get('container')->get("App\\GraphQL\\TestProvider")->getSomething(...$services->get('container')->get('overblog_graphql.arguments_transformer')->getArguments(["amount" => "Int!", "yes" => "Boolean"], $args, $info));
    },
```

Second issue is when `RequestService $requestService` argument is returned I get a following error:
`Failed to parse GraphQL metadata from file "/src/GraphQL/Types/RootQuery.php".`

RootQuery looks like this.

```<?php
declare(strict_types=1);

namespace App\GraphQL\Types;

use Overblog\GraphQLBundle\Annotation\Type;

#[Type]
final class RootQuery
{
    public function __construct()
    {
    }
}

```

Any suggestion how to make it work?
