### ISSUE TITLE
Could not find type with alias "Subscription". Did you forget to define it?

### ISSUE THREAD

**Issue by chou666** [overblog/GraphQLBundle#1129]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 1.0.0

I try to update from 0.15.1 to 1.0.0 (Symfony 5.4.27) with config:
```
overblog_graphql:
    definitions:
        config_validation: true
        schema:
            query: Query
            mutation: Mutation
            types:
              - <a lot>
```

When I clear the cache, I have the following error:

`Could not find type with alias "Subscription". Did you forget to define it? `

This error is not present with 0.15.1. An idea ? I see subscription experimental feature, is there a way to disable it ?
Maybe a missing configuration ?

**Comment by chou666** [comment]
@mcg-web thanks for the answer.

I define the Subscription type as:
```
Subscription:
    type: object
    config:
        fields:
            id:
                type: ID!
```
And no more error. Thanks for your help !
