### ISSUE TITLE
Help: Unclear how to use validation "link" with mutation/input objects

### ISSUE THREAD

**Issue by joesaunderson** [overblog/GraphQLBundle#1180]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 1

I am trying to use the validation linking as documented [here](https://github.com/overblog/GraphQLBundle/blob/master/docs/validation/index.md#linking-to-class-constraints) but I am struggling, and getting exceptions. 

Mutation:

```
EntityMutation:
    type: object
    heirs:
        - Mutation
    config:
        fields:
            edit_Entity:
                type: "Entity!"
                args:
                    entityId:
                        type: "ID!"
                    set:
                        type: "EntityEditInput!"
                        validation: cascade
                resolve: '@=query("App/Resolver::editEntity", args)'
```

Input Object

```
EntityEditInput:
    type: input-object
    config:
        fields:
            displayName:
                type: "String"
                validation:
                    link: 'App\Entity::$Name'
```

Exception

```
Property Overblog\\GraphQLBundle\\Validator\\ValidationNode::$Name does not exist
```

I noted this was mentioned [here](https://github.com/overblog/GraphQLBundle/blob/master/docs/validation/index.md#context-of-linked-constraints) but can you help me understand what the "correct" way of linking class constraints here would be (using an input object).
