### ISSUE TITLE
GraphQL Type System Definition to a config yaml

### ISSUE THREAD

**Issue by mcg-web** [overblog/GraphQLBundle#12]
Add a feature that convert  GraphQL [Type System Definition](https://facebook.github.io/graphql/#sec-Type-System-Definition):

```
interface Character {
  id: String!
  name: String
  friends: [Character]
  appearsIn: [Episode]
}
```

to config yaml file:

``` yaml
Character:
    type: interface
    config:
        fields:
            id:
                type: "String!"
            name:
                type: "String"
            friends:
                type: "[Character]"
            appearsIn:
                type: "[Episode]"
```

**Comment by akomm** [comment]
Do you want it as an alternative to yml config, or separate - lets say command - to generate the yml out of schema definition?

**Comment by mcg-web** [comment]
hi @akomm,
the need has change since... Now that **webonyx/graphql-php** supports Type System Definition to schema natively, graphql definition we be an easy way to write the schema. This solution will be more reusable than yaml, xml or php definition...

**Comment by enumag** [comment]
I think I might have found a work-around...

First define a SchemaFactory:

```
<?php declare(strict_types = 1);

namespace App\GraphQL;

use GraphQL\Type\Schema;
use GraphQL\Utils\BuildSchema;

class SchemaFactory
{
	public static function create(string $rootDir): Schema
	{
		// TODO: Add caching according to http://webonyx.github.io/graphql-php/type-system/type-language/#performance-considerations
		$contents = file_get_contents($rootDir . '/config/graphql/types/schema.graphql');

		return BuildSchema::build($contents);
	}
}
```

Then register the schema in services.yml:

```
    overblog_graphql.schema_default:
        factory: 'App\GraphQL\SchemaFactory:create'
        arguments:
            - %kernel.project_dir%
```

And add the schema.graphql file:

```
schema {
    query: Query
}

type Query {
    greetings(input: HelloInput!): String!
}

input HelloInput {
    firstName: String!
    lastName: String
}
```

What I don't understand however is how to define the resolver needed for the `greetings` query to work. Currently it throws this error:

```
Cannot return null for non-nullable field Query.greetings.
```

I know why, I didn't define anywhere how the greetings query should respond after all. But how do I fix it?
