### ISSUE TITLE
Access expresion and validation at query level.

### ISSUE THREAD

**Issue by Lube** [overblog/GraphQLBundle#124]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Version/Branch   | x.y.z

Setting access expression at query level, and prevent database access if user doesnt have to those queries.

**Comment by mcg-web** [comment]
Hi @Lube, 
can you give an example to explain the difference between what you asking for and the current `access` feature please?

**Comment by ooflorent** [comment]
@Lube have you tried using the Symfony security layer?

1. Add a firewall targeting your endpoint

    ```yml
    firewall:
      graphql:
        pattern: ^/graphql
        stateless: true
        <YOUR_PROVIDER>: <CONFIG>
    ```

2. Set an access_control

    ```yml
    access_control:
      - { path: ^/graphql, roles: IS_AUTHENTICATED_FULLY}
    ```

**Comment by VincentClair** [comment]
I don't know if its related, but i have a problem to get user in `resolve` property.
I'm fully authenticated for rest routes, but when I attempted to access to graphql, user is set anonymous.
It's probably a misconfiguration at symfony level, but maybe you have a suggestion?
Thanks

**Comment by VincentClair** [comment]
I have only set this in rooting:
```
overblog_graphql_endpoint:
    path: /graphql
    defaults:
        _controller: OverblogGraphQLBundle:Graph:endpoint
        _format: "json"
```
and in security:
```
    access_control:
        - { path: ^/graphql,               roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
```
and finally the firewalls:
```
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/auth/form$
            anonymous: true

        token:
            pattern: ^/token$
            security: false

        secured:
            pattern: ^/
            guard:
                authenticators:
                    - acme_superadmin.token_authenticator
                    - acme_app.token_authenticator
                entry_point: acme_app.token_authenticator
            saml:
                username_attribute: '%sso_saml_username_attribute%'
                check_path: /saml/acs
                login_path: /saml/login
                always_use_default_target_path: true
                user_factory: acme_user.user_manipulator
            form_login_ldap:
                login_path: /#/sign-in
                check_path: /auth/login
                service: ldap
                dn_string: '%ldap_binddn%'
                require_previous_session: false
                always_use_default_target_path: true
            form_login:
                login_path: /#/sign-in
                check_path: /auth/login
                require_previous_session: false
                always_use_default_target_path: true
            logout:
                path: /saml/logout
            anonymous: ~
            remember_me:
                secret:   '%secret%'
                lifetime: '%remember_me_lifetime%'
```
