### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by VincentClair** [overblog/GraphQLBundle#128]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.8.0

Is there a way to upload files through graphql?
Does the bundle manage multipart request?

Here is a related proposal for Apollo: https://github.com/apollographql/apollo/issues/65.

**Comment by mcg-web** [comment]
Hi, yes it is possible, you must use request to get your file in your mutation resolver, you can inject it using the object **request** in the expression language...

**Comment by ooflorent** [comment]
@mcg-web Could you provide an example? :trollface:

**Comment by mcg-web** [comment]
Here an example using relay mutation:

* **Schema**

```yaml
RootMutation:
    type: object
    config:
        fields:
            uploadFile:
                builder: "Relay::Mutation"
                builderConfig:
                    inputType: UploadFileInput
                    payloadType: UploadFilePayload
                    mutateAndGetPayload: "@=mutation('upload_file', [request, value['title']])"

UploadFilePayload:
    type: relay-mutation-payload
    config:
        fields:
            files: {type: "[String!]!" }

UploadFileInput:
    type: relay-mutation-input
    config:
        fields:
            title: {type: "String!"}
```

* **Mutation**

```php
    public function uploadFile(\Symfony\Component\HttpFoundation\Request $request, $title)
    {
        /** @var \Symfony\Component\HttpFoundation\FileBag; $requestFiles */
        $requestFiles = $request->files;
        if (!$requestFiles->has('myFile')) {
            throw new UserError(sprintf('File "%s" is required.', $fileFieldName));
        }
        /** @var \Symfony\Component\HttpFoundation\File\UploadedFile $file */
        $file = $requestFiles->get('myFile');
        // here do some work on your uploaded file
        return [$title];
    }
```

@ooflorent done! :trollface:
