### ISSUE TITLE
Trying to install GraphQLBundle, error in doc section (HTML content inside)

### ISSUE THREAD

**Issue by MGDSoft** [overblog/GraphQLBundle#129]
Hi :-),

I am trying to install this bundle following the instructions but when I go to localhost/graphiql in doc section I get html document from localhost/. Sorry if its a dumb question :/ but I am a newbie with graphQL

[Error IMG](https://imgur.com/RL6k7vQ)

My current sf version: 3.2.7 

```yml
# app/config/graphql/Query.types.yml
Query:
    type: object
    config:
        description: "A humanoid creature in the Star Wars universe."
        fields:
            user:
                type: "User"
                resolve: "@=resolver('myresolver')"
```

```yml
# app/config/graphql/User.types.yml
User:
    type: object
    config:
        description: "User"
        fields:
            id:
                type: "String!"
            name:
                type: "String"
```

```yml
# app/config/services.yml

services:

    myresolver:
        class: AppBundle\Service\MyResolver
        tags:
            - { name: overblog_graphql.resolver, alias: myresolver, method: resolveMyResolver }
```

```php
# src/AppBundle/Service/MyResolver.php

namespace AppBundle\Service;

class MyResolver
{
    public function resolveMyResolver()
    {
        return ['id' => 1, 'name' => 'Luke'];
    }
}
```

**Comment by mcg-web** [comment]
Hi, 

Here the error:

```
services:  
  myresolver:
        class: AppBundle\Service\MyResolver
        arguments: ['@overblog_graphql.promise_adapter']
        tags:
            - { name: form.type, alias: myresolver, method: resolveMyResolver }
```

wrong tag name, replace **form.type** by **overblog_graphql.resolver**
