### ISSUE TITLE
Bypass sub node value in values.value for enum type is accepted

### ISSUE THREAD

**Issue by mcg-web** [overblog/GraphQLBundle#13]
```yaml
Episode:
    type: enum
    config:
        values:
            NEWHOPE:
                value: 4
            EMPIRE:
                value: 5
            JEDI:
                value: 6
```

Should be equivalent to:

```yaml
Episode:
    type: enum
    config:
        values:
            NEWHOPE: 4
            EMPIRE: 5
            JEDI:  6
```
