### ISSUE TITLE
[Feat] graphiql - authentication token 

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#131]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | ^0.7.1

I want graphiql to send an authentication token to server. The package you use allows graphiql interface [customization](https://github.com/graphql/graphiql#usage). For example you can add input fields into the toolbar.

Currently you use the default graphiql interface without any customization.

It would be convenient, if I could define the following configuration for an endpoint:

```yml
# app/config/config_dev.yml
# overblog_graphql.definitions.schema
authentication:
  # optionally namespaced by endpoint name specified in overblog_graphql.definitions.schema
  send_method: "header" # header, query-string, ...
  fields: # fields to send using specified method
    access-token: "myaccesstoken"
```

Currently you need to override/extend the default template, which is unsafe.

**Comment by mcg-web** [comment]
Hi,
that's true but if you using JWT auth the token is dynamic so we must implement a way to send them to server... I'll see how to add this!

**Comment by akomm** [comment]
Currently working around it the following way:

```yml
# app/config/config_dev.yml
parameters:
  overblog_graphql.graphiql_template: 'graphiql.html.twig'
```
```twig
{# app/Resources/views/graphiql.html.twig #}
{% extends 'OverblogGraphQLBundle:GraphiQL:index.html.twig' %}

{% block graphql_fetcher_headers %}
  headers = {
    "Accept": "application/json",
    "Content-Type": "application/json",
    "access-token": "sometokenhere"
  };
{% endblock graphql_fetcher_headers %}
```

Isn't very cool but easy to get going.
