### ISSUE TITLE
[Feat] allow omitting resolver alias in tag config

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#134]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.7.1

When omitting alias for an resolver would implicitly set the alias to be equal the service class name, combined with [this feature request](https://github.com/overblog/GraphQLBundle/issues/133), a lot of boilerplate configuration could be saved using a bundle like [DunglasActionBundle](https://github.com/dunglas/DunglasActionBundle). You would not need to configure any  resolver services at all, as long as you implement a single resolve function per class (__invoke).

**Comment by mcg-web** [comment]
Ok I understand the need, is true that the bundle require a lot of configuration, we must work on a flow to ease `resolvers` and `mutations` definitions.... In first step i added #133.

**Comment by akomm** [comment]
I was about checking out to make a PR, this was  the fastest reaction I ever experienced!

```yml
AppBundle\GraphlQL\Resolver\WorkflowsResolver:
    class: AppBundle\GraphQL\Resolver\WorkflowsResolver
    autowire: true
    tags:
      - { name: overblog_graphql.resolver, method: '__invoke', alias: 'AppBundle\GraphQL\Resolver\WorkflowsResolver' }
```
Should be defaulted from:
```yml
services:
  AppBundle\GraphlQL\Resolver\WorkflowsResolver:
    class: AppBundle\GraphQL\Resolver\WorkflowsResolver
    tags:
      - { name: overblog_graphql.resolver }
```

This could be the default behavior without BC break. And with some extras, like the DunlasActionBundle it would be possible to auto-tag & wire so you don`t even need to provide this. It should not be be tied to another bundle, but it saves already boiler plate without.  The usage of the bundle can be proposed in docs as a best practice, if you agree.

- Resolver/Mutation services become thin. They do not handle 100 different resolves/mutations: Concern separation.
- You don't have to write the config for resolver/mutation services. 
- It is all compile time
