### ISSUE TITLE
Schema should throw on duplicated fields

### ISSUE THREAD

**Issue by ooflorent** [overblog/GraphQLBundle#14]
The following should throw an error or raise a warning.

```yml
Foo:
  type: object
  config:
    fields:
      a: {type: String}
      a: {type: Int}
```
