### ISSUE TITLE
Having 1 object that is both InputType and OutputType

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#152]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? |no
| BC Break report? |no
| RFC?             |no

I want to create a new type called `Coordinate(latitude: Float!, longitude: Float!)` that I want to use as both Input and OutputType. Current YAML doesn't allow this, as it forces you to choose between either `object` or `input-type`. Is there any reason for this? I see that a lot of the build in types implement both `InputType` and `OutputType`.

**Comment by mcg-web** [comment]
Hi @ruudk,

the difference between input  and output types come from GraphQL it self (two types must not have the same name).  Output types also accepts resolvers and not Input types. A solution to be DRY is using yaml  anchors feature:

```yaml
Coordinate:
  type: object
  config: 
    fields: &CoordinateFields
      latitude: {type: Float!}
      longitude: {type: Float!}

CoordinateInput:
  type: input-object
  config: 
    fields:
       <<: *CoordinateFields
```

Maybe I'm   missing something?
