### ISSUE TITLE
Unrecognized option fieldsDefaultPublic 

### ISSUE THREAD

**Issue by 3DRacers** [overblog/GraphQLBundle#154]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.8.3

The option seems to not being recognized

eg:
```
SocialProfile:
    type: object
    fieldsDefaultPublic: "@=hasPermission(object, 'EDIT')"
    config:    
```

or:
```
SocialProfile:
    type: object
    config:
        fieldsDefaultPublic: "@=hasPermission(object, 'EDIT')"
```
