### ISSUE TITLE
Any there good recipes for arguments validation using Symfony validator component?

### ISSUE THREAD

**Issue by ssimplix** [overblog/GraphQLBundle#156]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? |no
| RFC?             | no
| Version/Branch   | 0.8.3

Hi. I want to validate my arguments, e.g. for registration mutation, and I want to validate it via [Symfony validation](http://symfony.com/doc/current/validation.html). Didn't find anything about validation in docs and don't really know how to implement this elegant. Can you show some examples please and extend docs with it?

**Comment by mcg-web** [comment]
Hi, the best way is to create [**custom scalar using the service way**](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/type-system/index.md) and inject the validator directly . Here an example to validate emails:

```yaml
services:
    AppBundle\EmailType:
        # only for sf < 3.3
        #class: AppBundle\EmailType
        arguments:
            - "@validator"
        tags:
            - { name: overblog_graphql.type, alias: Email }
```
```php
<?php

namespace AppBundle;

use GraphQL\Error\InvariantViolation
use GraphQL\Language\AST\Node;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class EmailType extends CustomScalarType
{
    public function __construct(ValidatorInterface $validator)
    {
        $this->validator = $validator;
        parent::__construct([
            'name' => $this->getName(),
            'serialize' => [$this, 'serialize'],
            'parseValue' => [$this, 'parseValue'],
            'parseLiteral' => [$this, 'parseLiteral'],
        ]);
    }

    /**
     * @param string $value
     *
     * @return string
     */
    public function serialize($value)
    {
        return $value;
    }
 
    /**
     * @param mixed $value
     *
     * @return mixed
     */
    public function parseValue($value)
    {
        $this->validate($value);
        return $value;
    }
 
    /**
     * @param Node $valueNode
     *
     * @return string
     */
    public function parseLiteral($valueNode)
    {
        $this->validate($valueNode->value);
        return $valueNode->value;
    }

    private function validate($value)
    {
        $violations = $this->validator->validate($value, array(
            new Assert\Email(),
            new Assert\NotBlank(),
        ));
        if (0 !== count($violations)) {
            $message = "There are errors:\n";
            foreach ($violations as $violation) {
                $message .= '- '.$violation->getMessage()."\n";
            }
            throw new InvariantViolation($message);
        }
    }
}
```
after you can just use your new scalar type:

```yaml
# src/MyBundle/Resources/config/graphql/Human.types.yml
Human:
    type: object
    config:
        description: "A humanoid creature in the Star Wars universe."
        fields:
            email:
                type: "Email!"
                description: "The email of the character :D."
```
**note** custom types will be easier to create in next version, thanks again to auto mapping feature.

**Comment by ssimplix** [comment]
@mcg-web, seems like throwing `InvariantViolation` exception inside `EmailType` class produces ugly 500 error:

````json
{
  "error": {
    "code": 500,
    "message": "Internal Server Error",
    "exception": [
      {
        "message": "There are errors:\n- Значение адреса электронной почты недопустимо.\n",
        "class": "GraphQL\\Error\\InvariantViolation",
        "trace": [
          ...
        ]
      }
    ]
  }
}
````

When I replace `InvariantViolation` with `UserError` result is the same. Seems like throwing `UserError` exception only from resolver produces beauty GraphQL like error array.

**Comment by mcg-web** [comment]
It's the debug behavior. In no debug mode the violation while be catch. I'll add violation in white​ list...

**Comment by ssimplix** [comment]
@mcg-web, sorry, I think I didn't understand something. I have disabled displaying debug info in bundle config:

````yml
overblog_graphql:
    definitions:
        show_debug_info: false
        config_validation: %kernel.debug%
        schema:
            query: Query
            mutation: Mutation
    templates:
        graphiql: '%kernel.root_dir%/Resources/views/graphiql/index.html.twig'
````

Also I run Symfony without debug mode:

````php
// web/app.php
$kernel = new AppKernel('dev', false);
````

When I throw any exception from the type class (`InvariantViolation` or `UserError`), it produces 500 error:

````php
namespace AppBundle\GraphQL\Type;

use GraphQL\Language\AST\Node;
use GraphQL\Type\Definition\CustomScalarType;
use Overblog\GraphQLBundle\Error\UserError;
use Overblog\GraphQLBundle\Error\UserErrors;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class EmailType extends CustomScalarType
{
    private $validator;

    public function __construct(ValidatorInterface $validator)
    {
        $this->validator = $validator;

        parent::__construct([
            'name' => 'Email',
            'serialize' => [$this, 'serialize'],
            'parseValue' => [$this, 'parseValue'],
            'parseLiteral' => [$this, 'parseLiteral'],
        ]);
    }

    /**
     * @param string $value
     *
     * @return string
     */
    public function serialize($value)
    {
        return $value;
    }

    /**
     * @param mixed $value
     *
     * @return mixed
     */
    public function parseValue($value)
    {
        $this->validate($value);

        return $value;
    }

    /**
     * @param Node $valueNode
     *
     * @return string
     */
    public function parseLiteral($valueNode)
    {
        $this->validate($valueNode->value);

        return $valueNode->value;
    }

    private function validate($value)
    {
        $violations = $this->validator->validate($value, [
            new Assert\NotBlank(),
            new Assert\Email(),
        ]);

        if (count($violations) > 0) {
            $errors = [];

            foreach ($violations as $violation) {
                $errors[] = new UserError($violation->getMessage());
            }

            throw new UserErrors($errors);
        }
    }
}
````

JSON response with disabled debugging everywhere:

````json
{
  "error": {
    "code": 500,
    "message": "Internal Server Error"
  }
}
````

JSON response with enabled debugging:

````json
{
  "error": {
    "code": 500,
    "message": "Internal Server Error",
    "exception": [
      {
        "message": "",
        "class": "Overblog\\GraphQLBundle\\Error\\UserErrors",
        "trace": [
          ...
        ]
      }
    ]
  }
}
````

What should I do to get response like this one?

````json
{
  "data": {
    "register": null
  },
  "errors": [
    {
      "message": "Invalid email.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "register"
      ]
    }
  ]
}
````
