### ISSUE TITLE
how subQuery Works ?

### ISSUE THREAD

**Issue by blade503** [overblog/GraphQLBundle#171]
I would like to know how can we make a subQuery in a query ? For example i have a car and i would like to call a subquery giving her a param for the format of my picture. How do i declare my subQuery on my main query ? 

I used to work with youshido bundle but it doesn't match my needs. This bundle works better but i don't succeed to see how i can "import" a subquery in a query.

**Comment by mcg-web** [comment]
Can you give an example of you schema please? what do you mean by sub-query ?

**Comment by blade503** [comment]
{
  user(id: 10010) {
    id
    onlineCarsCount
    displayName
    ownerReviewAverage
    tenantReviewAverage
    globalReviewAverage
    registeredAt
    answerPercent
    rentalsDoneCount
    answerDelay
    userTempMainPhoto(format: "person__profile_public__thumb")
    ratingUserAsOwner: ratingUser(type: "owner") {
      id
      userSender {
        displayName
        userTempMainPhoto(format: "person__profile_public_list__thumb")
      }
      rate
      title
      message
      createdAt
    }
  }
}

I would like to do such as ratingUser or userTempMainPhoto in this query. Give an argument. The query ratingUser can be called alone as a root query or can be call in user as a subquery. How could i define it to work like this ?

**Comment by blade503** [comment]
After doing some research the thing that i call subQuery would be an object Field.

Such as in this example

`query UserPosts{
    posts(userId:45) {
        id
        title
        text
        createdAt
        updatedAt
        comments(last:5) {
            id
            text
            user {
                id
                name
            }
        }
    }
}`

Here the object field would be comments(last: 5). I hope i could be more easy to inderstand with those explanations

**Comment by mcg-web** [comment]
Here your schema

```graphql
schema {
  query: Query
}

type Query {
   posts(userId: Int!): [Post!]!
}

type Post {
  id: ID!
 title: String!
 text: String!
 createdAt: String!
 updatedAt: String!
 comments(last: Int = 5): [Comment!]!
}

type Comment {
  id: ID! 
  text: String!
  user: User!
}

type User {
  id: ID!
  name: String!
}
````

in yaml this is equivalent to:

```yaml
# app/config/config.yml
overblog_graphql:
    definitions:
        schema:
            query: Query
```

```yaml
# src/AppBundle/config/my-schema.types.yml
Query:
    type: object
    config:
        fields:
            posts:
                type: ' [Post!]!'
                args:
                    userId: { type: Int! }
                resolve: '@=...'  # here your resolver

Post:
    type: object
    config:
        fields:
            id: { type: ID! }
            title: { type: String! }
            text: { type: String! }
            createdAt: { type: String! }
            updatedAt:  { type: String! }
            comments: 
                type: '[Comment!]!'
                resolve: '@=...'  # here your resolver
                args:
                    last: {type: Int, defaultValue: 5}
# ...
```
