### ISSUE TITLE
Resolver for child queries

### ISSUE THREAD

**Issue by PauuloG** [overblog/GraphQLBundle#175]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Version  | ^0.8.6

Hey ! I'm trying to figure out how to configure a query that would result in this shorthand schema :
```graphql
type Query {
  # Fetches an object given its ID
  node(
    # The ID of an object
    id: ID!
  ): Node
  viewer: Viewer
}

# Viewer object used to fetch collections as entrypoint
type Viewer {
  # Fetch latest translation keys
  allTranslations(after: String, first: Int, before: String, last: Int): AllTranslationsConnection
}
```

Where a query (ultimately a relay query) would look like :
```graphql
{
    viewer {
        allTranslations(first: 50) {
            id
            name
        }
    }
}
```

Unfortunately I can't figure how to setup the resolver part in order for `allTranslations` to call the `resolveAllTranslations`. Here is my config : 
```yaml
Query:
    type: object
    config:
        description: "Root Query"
        fields:
            node:
                builder: Relay::Node
                builderConfig:
                    nodeInterfaceType: Node
                    idFetcher: '@=resolver("node", [value])'
            viewer:
                type: Viewer!
#...
Viewer:
    type: object
    config:
        description: "Viewer object used to fetch collections as entrypoint"
        fields:
            allTranslations:
                type: "AllTranslationsConnection"
                description: "Fetch latest translation keys"
                argsBuilder: Relay::Connection
                resolve: '@=resolver("translationKey_all", [args])'
```

Could you point me towards an example or some doc for this ?
Thanks for the great work !

**Comment by mcg-web** [comment]
hi, you must create a tagged service to do that:

```yaml
services:
    AppBunble\GraphQL\CustomResolver:
        # only for sf < 3.3
        #class: AppBunble\GraphQL\CustomResolver
        tags:
            - { name: overblog_graphql.resolver, alias: translationKey_all, method: resolveAllTranslations }
```

your resolver must returns a `Connection`, you can use the builder for that...

[here an example of a resolver](https://github.com/mcg-web/graphql-symfony-doctrine-sandbox/blob/master/src/AppBundle/GraphQL/Relay/Resolver/FactionResolver.php#L36-L82)
and [the service definition](https://github.com/mcg-web/graphql-symfony-doctrine-sandbox/blob/master/src/AppBundle/Resources/config/graphql-relay.yml#L8-L14)

**Comment by PauuloG** [comment]
Hey ! Thanks for the quick answer

I was not clear enough I think :) ! Here are my services 
```
 app.graph.resolver.faction:
        class: TranslationBundle\GraphQL\Relay\Resolver\TranslationKeyResolver
        tags:
            - { name: overblog_graphql.resolver, alias: "translationKey_all", method: "resolveAll" }
            - { name: overblog_graphql.resolver, alias: "viewer", method: "resolveViewer" }
```

What I would like to do is in the `viewer` resolver be able to tell which resolver to call ultimately (translationKey_all here, but could also be another field like translationKey_single).

Right now I manage to have the `viewer` resolver called but don't know how call the right resolver for the child-query translationKey_all (I mean how to decide which resolver to call not the actual call which is ok).
