### ISSUE TITLE
path "overblog_graphql_types.Bladibla" cannot be overwritten.

### ISSUE THREAD

**Issue by hgraca** [overblog/GraphQLBundle#216]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.9.1

Hi, 

I have installed this bundle and followed the examples at https://github.com/symfony/recipes-contrib/tree/master/overblog/graphql-bundle/0.9 and https://github.com/mcg-web/graphql-symfony-doctrine-sandbox but I keep getting:

`(1/1) ForbiddenOverwriteExceptionConfiguration path "overblog_graphql_types.Bladibla" cannot be overwritten. You have to define all options for this path, and any of its sub-paths in one configuration section.`

My config is as follows:

```yml
# app/config/config.yml
overblog_graphql:
    definitions:
        internal_error_message: "An error occurred, please retry later or contact us!"
        use_classloader_listener: false
        cache_dir: '%kernel.root_dir%/../src/UserInterface/Mobile'
        class_namespace: "Foo\\Bar\\UserInterface\\Mobile"
        config_validation: "%kernel.debug%"
        schema:
            query: Query
            mutation: Mutation
        mappings:
            auto_discover: false # to disable bundles and root dir auto discover
            types:
                -
                    type: yaml
                    dir: '%kernel.root_dir%/../lib/config-bundle/src/Resources/config/user_interface/mobile'
                -
                    type: yaml
                    dir: '%kernel.root_dir%/../lib/config-bundle/src/Resources/config/user_interface/mobile/bla_di_bla'
```

```yml
# lib/config-bundle/src/Resources/config/user_interface/mobile/Query.types.yml
Query:
    type: object
    config:
        description: "..."
        fields:
            bla_di_bla:
                type: "Bladibla"
                args:
                    id:
                        description: "id of the Bladibla"
                        type: "Int!"
                resolve: "@=resolver('bla_di_bla', [args])"
```

```yml
# lib/config-bundle/src/Resources/config/user_interface/mobile/bla_di_bla/Bladibla.types.yml
Bladibla:
    type: object
    config:
        description: "..."
        fields:
            id:
                type: "Int!"
                description: "The id of the Bladibla."
            title:
                type: "String"
                description: "The title of the Bladibla."
```

```yml
# resolver.yml
services:
    bar.user_interface.graphql.bla_di_bla.resolver:
        alias: bar.core.bla_di_bla.repository.bla_di_bla
        tags:
            - { name: overblog_graphql.resolver, alias: "bla_di_bla", method: "get" }
```

Someone has any idea what is going wrong? 

Tkx in advance.
