### ISSUE TITLE
AbstractProxyResolver bug?

### ISSUE THREAD

**Issue by hgraca** [overblog/GraphQLBundle#220]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.9.0

I think the `AbstractProxyResolver` is not working properly, here:
https://github.com/hgraca/GraphQLBundle/blob/d18b689681b96597257762dd8f615df3605a0b45/Resolver/AbstractProxyResolver.php#L47

If I make the query:

```gql
query BladiblaQuery {
  bla_di_bla(id: 1) {
    title
  }
}
```
I get the error:

> Type error: Argument 1 passed to Foo\\Bar\\...\\BladiblaResolver::getOne() must be of the type integer, object given

where the signature of the method is `getOne(int $id): Bladibla`, but xdebug shows that the `AbstractProxyResolver` is trying to inject an `Argument` object with the `id` inside.

I can fix this by exploding the arguments, like `return call_user_func_array($func, $funcArgs->getRawArguments());`, but then it breaks the usage for the mutator:

```gql
mutation MessageMutator($input: SendMessageInput!) {
  sendMessage(input: $input) {
    clientMutationId
  }
}

# query variables:
{
  "input": {
    "bumpId": 33,
    "message": "Some message",
    "clientMutationId": "6d9d8cd3-f160-4f0e-932f-fd8849c4e315"
  }
}
```

> Type error: Too few arguments to function Overblog\\GraphQLBundle\\GraphQL\\Relay\\Mutation\\MutationFieldResolver::__invoke(), 1 passed and exactly 4 expected

Because `MutationFieldResolver::__invoke($args, $context, $info, \Closure $mutateAndGetPayloadCallback)` is only receiving an array with an `input` key and the graphql query arguments inside. 

Let me know if you have any ideas for solving this, otherwise I will ask for time to fix this here in the company and will try to solve it myself.

**Comment by mcg-web** [comment]
Hi,

Can you give me your schema configuration please?

**Comment by hgraca** [comment]
Sure, here u go:

```yml
# app/config/config.yml
overblog_graphql:
    definitions:
        internal_error_message: "An error occurred, please retry later or contact us!"
        use_classloader_listener: false
        cache_dir: '%kernel.root_dir%/../src/UserInterface/Mobile/Type'
        class_namespace: "Foo\\Bar\\UserInterface\\Mobile\\Type"
        config_validation: "%kernel.debug%"
        show_debug_info: true
        schema:
            query: Query
            mutation: Mutation
        mappings:
            auto_discover: false # to disable bundles and root dir auto discover
            types:
                -
                    type: yaml
                    dir: '%kernel.root_dir%/../lib/config-bundle/src/Resources/config/user_interface/mobile'
                    suffix: Type
```

Query config:

```yml
# lib/config-bundle/src/Resources/config/user_interface/mobile/QueryType.yml
Query:
    type: object
    config:
        description: "..."
        fields:
            bla_di_bla:
                type: "BlaDiBla"
                args:
                    id:
                        description: "..."
                        type: "Int!"
                resolve: "@=resolver('graphql.bla_di_bla.resolver', [args])"
```

```yml
# lib/config-bundle/src/Resources/config/user_interface/mobile/bla_di_bla/BlaDiBlaQueryType.yml
BlaDiBla:
    type: object
    config:
        description: "..."
        fields:
            id:
                type: "Int!"
                description: "The id of the service request."
            title:
                type: "String"
                description: "The title of the service request."

```

Mutator config:

```yml
# lib/config-bundle/src/Resources/config/user_interface/mobile/MutationType.yml
Mutation:
    type: object
    config:
        fields:
            sendMessage:
                builder: Relay::Mutation
                builderConfig:
                    inputType: SendMessageInput
                    payloadType: SendMessagePayload
                    mutateAndGetPayload: "@=mutation('graphql.message.mutator', [value['proposalId'], value['message']])"

```

```yml
# lib/config-bundle/src/Resources/config/user_interface/mobile/message/SendMessageMutationType.yml
SendMessageInput:
    type: relay-mutation-input
    config:
        fields:
            proposalId:
                type: "Int!"
            message:
                type: "String!"

SendMessagePayload:
    type: relay-mutation-payload
    config:
        fields:

```
