### ISSUE TITLE
[FEATURE] Improve expression language customization 

### ISSUE THREAD

**Issue by mcg-web** [overblog/GraphQLBundle#262]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | `0.11 \| 0.12`

Right now adding custom expression language functions is not that easy. 
Is the reason why, I'm proposing to introduce tagged services `overblog_graphql.expression_function`. Giving users the ability to use DI autoconfigure (or the out of the box auto mapping feature for symfony < 3.3 version) to easily inject their custom functions. This feature will helps user create simple resolver without having to leave config file, this will also improve performance by removing an external resolver call.

**edit:** treating json string directy in your resolver
- before:
```yaml
Object:
  type: object
  config:
    fields:
      name:
        type: String!
        resolve: "@=resolver('json_decode', [value.json_data, true])['name']" 
```
```php
namespace App\GraphQL\Resolver;

use Overblog\GraphQLBundle\Definition\Resolver\AliasedInterface;
use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;

class JsonResolver  implements ResolverInterface, AliasedInterface
{
    public function jsonDecode($json, $assoc)
    {
        return json_decode($json, $assoc);
    }

    public static function getAliases()
    {
        return [
            'jsonDecode' => 'json_decode',
        ];
    }
}
```

- after:
```yaml
Object:
  type: object
  config:
    fields:
      name:
        type: String!
        resolve: "@=json_decode(value.json_data, true)['name']" 
```

```php
namespace App\ExpressionLanguage;

use Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction;

class JsonDecode extends ExpressionFunction
{
    public function __construct()
    {
        parent::__construct(
            'json_encode',
            function ($json, $assoc) {
                return sprintf('json_decode(%s, %s)', $value, $assoc);
            }
        );
    }
}
```

```yaml
App\ExpressionLanguage\JsonDecode:
  tags: ['overblog_graphql.expression_function']
```
