### ISSUE TITLE
Custom Scalar type troubles

### ISSUE THREAD

**Issue by SebScoFr** [overblog/GraphQLBundle#270]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Version/Branch   | 0.10.2

I'm having a really hard time defining a custom scalar type based on the doc provided. I'm using SF4.

Here is my **config/packages/graphql.yaml**
```yml
overblog_graphql:
    definitions:
        schema:
            authentication:
                query: Main
                mutation: Authentication
            main:
                query: Main
        auto_mapping: false
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql"
                    suffix: ~
```
Here is my custom DateTime type under **config/graphql/types/custom/datetime.yaml**
```yml
DateTime:
    type: custom-scalar
    config:
        serialize: ["App\\Type\\DateTimeType", "serialize"]
        parseValue: ["App\\Type\\DateTimeType", "parseValue"]
        parseLiteral: ["App\\Type\\DateTimeType", "parseLiteral"]
```
Here is the **config/services.yaml**
```yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Type\:
        resource: '../src/Type'
        tags: ['overblog_graphql.type']

    App\Resolver\:
        resource: '../src/Resolver'
        tags: ['overblog_graphql.resolver']

    App\Mutation\:
        resource: '../src/Mutation'
        tags: ['overblog_graphql.mutation']
```
And here is the class under **src/Type/DateTimeType.php**
```php
<?php

namespace App\Type;

use GraphQL\Language\AST\Node;

class DateTimeType
{
    /**
     * @param \DateTime $value
     *
     * @return string
     */
    public static function serialize(\DateTime $value)
    {
        return $value->format('Y-m-d H:i:s');
    }

    /**
     * @param mixed $value
     *
     * @return mixed
     */
    public static function parseValue($value)
    {
        return new \DateTime($value);
    }

    /**
     * @param Node $valueNode
     *
     * @return string
     */
    public static function parseLiteral($valueNode)
    {
        return new \DateTime($valueNode->value);
    }
}
```
This setup gives me the error:

> Resolver "App\Type\DateTimeType" must be "GraphQL\Type\Definition\Type" "App\Type\DateTimeType" given.

If I add `extends GraphQL\Type\Definition\Type` to my PHP class, now the error is

> Catchable Fatal Error: Method App\Type\DateTimeType::__toString() must return a string value

Would it be possible to clarify the correct process for adding a custom scalar type in the doc?
Thanks for the awesome work on this bundle.

**Comment by mcg-web** [comment]
Hi try replacing this part:

```yaml
    App\Type\:
        resource: '../src/Type'
        tags: ['overblog_graphql.type']
```

by:

```yaml
services: 
   _instanceof:
        GraphQL\Type\Definition\Type:
            tags: ['overblog_graphql.type']
    App\Type\:
        resource: '../src/Type'
```
