### ISSUE TITLE
Why does field access control on field makes its parent return `null`?

### ISSUE THREAD

**Issue by Kocal** [overblog/GraphQLBundle#272]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | xxx

Hey, I encountered a problem on field access control. 

So I got this schema: 

```yml
Query:
  type: object
  config:
    fields:
      site:
        type: Site
        resolve: "@=resolver('site', [args])"
        access: "@=hasPermission(object, 'view')"
        args:
          id:
            type: "Int"

Site:
  type: object
  config:
    fields:
      alpGroups:
        type: "[AlpGroup]!"
        resolve: "@=resolver('alp_groups_for_site', [value])"

AlpGroup:
  type: object
  config:
    fields:
      id:
        type: Int!
      platform:
        type: Site!
        access: "@=hasPermission(object, 'view')"
```

The user has access to `site` and `site.alpGroups`, but he does not have access to `site.alpGroups.X.platform`.

Here is a small example of what the query can returns:
![image](https://user-images.githubusercontent.com/2103975/34816385-0b40f970-f6b5-11e7-93d2-ad64cd644dde.png)

However, when I try to access `site.alpGroups.X.platform`, every values of `data.site.alpGroups` are `null`. 
![selection_539](https://user-images.githubusercontent.com/2103975/34816369-029f2292-f6b5-11e7-83b2-80cfe733a320.png)

Why does it not return something like below? 
Did I misunderstand how field access works, or it's a bug?

```json
{
  "data": {
    "site": {
      "alpGroups": [
        {
          "id": 1,
          "platform": null
        },
        {
          "id": 2,
          "platform": null
        },
        {
          "id": 3,
          "platform": null
        },
        {
          "id": 4,
          "platform": null
        }
      ]
    }
  }
}

```

Thanks!

**Comment by mcg-web** [comment]
Hi @Kocal,

Does the user has access to every site in `site.alpGroups.X.platform`?
If this is the case can you try using very the type of site (array or object) in `site.alpGroups.X.platform` and `root.site`?
This can be done easily by accessing to the generated type resolvers.

**Comment by Kocal** [comment]
Nope, `site.alpGroups.X.platform` is a different site than `site` :confused: 

In our project, a platform is a _special site_ which has children sites.
`site` is a **children** of `site.alpGroups.X.platform`.

So, the owner of `site` should not have access to its site's parent

**Comment by mcg-web** [comment]
Ok. `"@=resolver('alp_groups_for_site', [value])"` returns an array of array or an array of object?

**Comment by Kocal** [comment]
It returns an array of object (a Doctrine entity)

**Comment by mcg-web** [comment]
Can you verify manually that both objects returns `true` for`$container->get('security.authorization_checker')->isGranted('view', $siteFromSite)` and 
`$container->get('security.authorization_checker')->isGranted('view', $siteFromAlpGroupsSite)` ?

**Comment by Kocal** [comment]
![image](https://user-images.githubusercontent.com/2103975/34819053-fe80b51a-f6bc-11e7-8d25-c31fef373b1c.png)
![image](https://user-images.githubusercontent.com/2103975/34819064-0391ef10-f6bd-11e7-96a3-74c5fc4943ec.png)

As expected, the user can view its site, but not the parent (platform) of its site.

**Comment by mcg-web** [comment]
Ok  I understand your bug

when using access if the return callback is false the protected field will be set to null but   if your field is not nullable all the parent will be set to null. The true bug here is the non return of the error in response `errors` section. 

So to fix this
```yaml
AlpGroup:
  type: object
  config:
    fields:
      id:
        type: Int!
      platform:
        type: Site # <- nullable
        access: "@=hasPermission(object, 'view')"
```
