### ISSUE TITLE
Casting resolver values

### ISSUE THREAD

**Issue by Kocal** [overblog/GraphQLBundle#295]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | .
| Version/Branch   | .

I think it should be nice if we were able to cast on-the-fly resolver values.

Imagine you have a whole codebase with bad types everywhere... (it's actually my case :sweat_smile:). In your resolvers you will be able to cast those bad types to good types!

**Before:**
```yml
Article:
  type: object
  config:
    fields:
      commentsCount:
        type: String! # we don't know the reason, but imagine it's a string
```

**After:**
```yml
Article:
  type: object
  config:
    fields:
      commentsCount:
        cast: int
        type: Int! # and now it's an int
```

The key `cast` is optional, but when it's specified, its value is passed to [settype](http://php.net/manual/fr/function.settype.php) function.

I don't really thinks it's hard to implement. Even me I think I can do it :trollface: 

Thanks

**Comment by mcg-web** [comment]
hi @Kocal,
this should work normaly without cast
```yaml
Article:
  type: object
  config:
    fields:
      commentsCount:
        type: Int! # and now it's an int
```
because this is already the [native behavior](https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/IntType.php#L68) of `webonyx/graphql-php` lib.
