### ISSUE TITLE
Confused about how to use ResolverMap with Service Container / DI

### ISSUE THREAD

**Issue by msheakoski** [overblog/GraphQLBundle#308]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.0

I am trying to update from the 0.10 to 0.11 way of doing things but the documentation for ResolverMap is really confusing for me. If somebody could answer these questions, I would greatly appreciate it!

1. How do I use the Service Container / DI? Previously, I had an expression `@=resolver` in my config and all dependencies would be properly loaded. In my 0.11 setup, I am passing my resolvers to the ResolverMap constructor. Although it works, it ends up instantiating all of the resolvers instead of lazy-loading them if the query asks for them. Am I doing this correctly or is there a better way?

2. With the new ResolverMap, does this require that I change the method signature of my resolvers? Previously it was simply `($args)` but now it seems to be `($value, $args, $context, $info)`.

### 0.10 setup:
```yaml
# config/graphql/types/Query.yaml
Query:
    type: object
    config:
        fields:
            fruits:
                type: "[String]!"
                args:
                    color:
                        type: String
                    shape:
                        type: String
                resolve: '@=resolver("App\\GraphQL\\Resolver\\Fruits", [args])'
```
```php
// src/GraphQL/Resolver/Fruits.php
use Overblog\GraphQLBundle\Definition\Argument;
use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;

class Fruits implements ResolverInterface
{
    protected $repo;

    public function __construct(FruitRepository $repo)
    {
        $this->repo = $repo;
    }

    public function __invoke(Argument $args)
    {
        return $this->repo->findBy($args);
    }
}
```
### 0.11 setup:
```graphql
# config/graphql/types/Query.graphql
type Query {
    fruits(
        color: String
        shape: String
    ): [String]!
}
```
```php
// src/GraphQL/ResolverMap.php
namespace App\GraphQL;

use App\GraphQL\Resolver\Fruits;
use Overblog\GraphQLBundle\Resolver\ResolverMap as BaseResolverMap;

class ResolverMap extends BaseResolverMap
{
    private $fruits;

    public function __construct(Fruits $fruits)
    {
        $this->fruits = $fruits;
    }

    protected function map()
    {
        return [
            "Query" => [
                "fruits" => $this->fruits,
            ],
        ];
    }
}
```
```php
// src/GraphQL/Resolver/Fruits.php
use Overblog\GraphQLBundle\Definition\Argument;
use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;

class Fruits implements ResolverInterface
{
    private $repo;

    public function __construct(FruitRepository $repo)
    {
        $this->repo = $repo;
    }

    public function __invoke($value, Argument $args)
    {
        return $this->repo->findBy($args);
    }
}
```
