### ISSUE TITLE
Add support for multiple "argsBuilder" 

### ISSUE THREAD

**Issue by Kocal** [overblog/GraphQLBundle#321]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | .
| Version/Branch   | .

As discussed on a [Slack thread](https://symfony-devs.slack.com/messages/C7PE69PU3/p1524727034000147), that would be awesome to  have the possibility to write something like that:

```yml
myField:
  argsBuilder: 
    - 
      builder: MyFirstArgsBuilder
      config: ...
    -
      builder: MySecondArgsBuilder
      config: ...
```

It would prevent to us to write something not flexible at all:

```php
class MyFirstArgsBuilder implements MappingInterface
{
    public function toMappingDefinition(array $config): array
    {
        $definition = [
            'foo' => [
                'type' => 'Int',
            ],
        ];

		return $definition;
    }
}


class MySecondArgsBuilder implements MappingInterface
{
    public function toMappingDefinition(array $config): array
    {
        $definition = [
            'bar' => [
                'type' => 'Int',
            ],
        ];

        return (new MyFirstArgsBuilder())->toMappingDefinition($config) + $definition;
    }
}

```

Also, it should handle argument name conflicts. For example, it should throw an exception if `MyFirstArgsBuilder` and `MySecondArgsBuilder` both provide `foo` argument. 

Thanks
