### ISSUE TITLE
Question: Interfaces and their implementations properties

### ISSUE THREAD

**Issue by Alsciende** [overblog/GraphQLBundle#324]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

```
overblog/graphql-bundle                         v0.10.3           
overblog/graphql-php-generator                  v0.6.0            
webonyx/graphql-php                             v0.11.6           
```

I have an issue where `Executor` complains that a non-nullable field is null when the object to return is from an implementation of an Interface and the property is from another implementation.

```
  - Cannot return null for non-nullable field File.versions.
     * vendor/webonyx/graphql-php/src/Executor/Executor.php:923
```

The object to return is from the class `Folder`, a sibling of `File`.

My (simplified) definitions are as follow:

```yaml
Path:
    type: interface
    config:
        fields:
            id:
                type: 'ID!'
            name:
                type: 'String!'
```

```yaml
File:
    type: object
    config:
        fields:
            id:
                type: 'ID!'
            name:
                type: 'String!'
            versions:
                type: '[Version]!'
        interfaces:
            - Path
```

```yaml
Folder:
    type: object
    config:
        fields:
            id:
                type: 'ID!'
            name:
                type: 'String!'
        interfaces:
            - Path
```

The query is:

```graphql
   tree {
        items {
            id
            name
            ... on File {
                versions{
                    fullName
                    downloadLink
                }
            }
        }
    }
```

The php classes `Folder.php` and `File.php` extend the class `Path.php`. Only `File.php` has a property `$versions`. The value `version` is only requested for the type `File`. But the Executor refuses to return a `Folder` object.

I "fixed" the issue by moving `$versions` to `Path.php`, but I don't understand what I'm doing wrong. If a property is defined for a type, why should it also be defined for all "siblings" of that type?
