### ISSUE TITLE
Fields public control is being checked during dump

### ISSUE THREAD

**Issue by martiis** [overblog/GraphQLBundle#329]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.0

When `graphql:dump-schema` command is used and schema contains
`public: "@=service('security.authorization_checker').isGranted('ROLE_ADMIN')"`
exception is being thrown: `[Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException]
  The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL.`

In command line there is no security token. Shouldn't this be only checked during request?

**Comment by mcg-web** [comment]
Hi `public` config is used to alter schema so it must always be process before schema is created. You should use `access` instead or create cli environments answering to each user profile. Maybe we could also add a way to simulate a user in this case.

**Comment by martiis** [comment]
But when using `access` field is still being resolved and later it tells that I don't have access. Would be a great option to have smth like pre access check or I can just check it at the resolver start.

**Comment by mcg-web** [comment]
Access is done on pre resolve so only when effectively resolving data (not on introspection). Public is done Everytime.

**Comment by martiis** [comment]
https://github.com/overblog/GraphQLBundle/blob/47849e3b9b8f949dcd07138e9e2ab52f12854506/Resolver/AccessResolver.php#L26

My guess that its being checked by this :)

For mutations its pre checked, but if I use queries, field is being resolved and then returned value is being checked if I can access it.

In my case:
```
Query:
    type: object
    config:
        fields:
            securedField:
                access: "@=service('security.authorization_checker').isGranted('ROLE_USER')"
                resolve: "@=resolver('my_top_secret_resolver', [args])"
                type: 'SuperSecretObject'
```

Am not logged, anonymous. Checked with xdebug resolver is being called.
