### ISSUE TITLE
Connection without the Connection suffix

### ISSUE THREAD

**Issue by sylfabre** [overblog/GraphQLBundle#341]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Version/Branch   | 0.11

The following type definition works like a charm:

```yaml
JohnConnection:
    type: relay-connection
    config:
        nodeType: String
        connectionFields:
            totalCount:
                type: "Int!"
                description: "Number of items in this collection"
```

If you remove the `Connection` suffix, it breaks:

```yaml
John:
    type: relay-connection
    config:
        nodeType: String
        connectionFields:
            totalCount:
                type: "Int!"
                description: "Number of items in this collection"
```

with the following message: 

Unrecognized option "_relay_connection_config" under "overblog_graphql_types.John"
