### ISSUE TITLE
Extending relay-connection

### ISSUE THREAD

**Issue by sylfabre** [overblog/GraphQLBundle#342]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Version/Branch   | 0.11.1

The following definitions leads to an error

```yaml
# TotalCountConnection.types.yaml

TotalCountConnection:
    type: relay-connection
    config:
        connectionFields:
            totalCount:
                type: Int!
                description: "Number of items in this collection"
```

```yaml
# TestConnection.types.yaml
TestConnection:
    type: TotalCountConnection
    config:
        nodeType: String
```

The error is 
**Unrecognized option "_TotalCountConnection_config" under "overblog_graphql_types.TestConnection"**

I'm trying to make a default connection type with the `totalCount` field to use whenever I need a connection with this field
