### ISSUE TITLE
Make decorator-usage as type a compile time error, instead of runtime

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#350]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | dev-master

First of all: nice feature. I used "decorators" often and now they are an actual feature and I can prevent them from going into the schema! :+1: 

Is it actually possible to throw error at compile time, when I have:

```yaml
SomeType:
  type: 'object'
  config:
    fields:
      someField: { type: 'SomeDecoratorType' }
```

While `SomeDecoratorType` is an object with `config.decorator: true`.
