### ISSUE TITLE
Hack to make persist context in older version

### ISSUE THREAD

**Issue by mcg-web** [overblog/GraphQLBundle#367]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | hack
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.9|0.10

Here a fast hack to make context an ArrayObject in 0.9:

```php
<?php

namespace App\EventListener;

use Overblog\GraphQLBundle\Event\ExecutorContextEvent;

class PersistContextListener
{
    public function onExecutorContextEvent(ExecutorContextEvent $event)
    {
        // here the hack to make context an ArrayObject
        $persistContextCallable = \Closure::bind(function () {
            $this->executorContext = new \ArrayObject();
        }, $event, get_class($event));

        $persistContextCallable();
    }
}
```

 ```yaml
app.persist_context:
        class: App\EventListener\PersistContextListener
        tags:
            - { name: kernel.event_listener, event: graphql.executor.context, method: onExecutorContextEvent }
```
