### ISSUE TITLE
How to use resolver as services?

### ISSUE THREAD

**Issue by sylfabre** [overblog/GraphQLBundle#373]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.4

I'm using Symfony 4 and my resolvers are autowired services.

Let's say I've defined the following types:

```yaml
Query:
    type: object
    config:
        fields:
            me:
                type: User
                resolve: '@=resolver("App\\GraphQL\\Resolver\\UserResolver::me")'
            user:
                type: User
                args:
                    id: Int
                resolve: '@=resolver("App\\GraphQL\\Resolver\\UserResolver::user", [args])'

                
User:
    type: object
    config:
        fields:
            id:
                type: Int
            
            name:
                type: String
                resolve: '@=resolver("App\\GraphQL\\Resolver\\UserResolver::getName")'
                
            parent:
                type: Parent
                
Parent:
    type: object
    config:
        fields:
            id:
                type: Int
            
            name:
                type: String
                resolve: '@=resolver("App\\GraphQL\\Resolver\\ParentResolver::getName")'
            
            name2:
                type: String

```

Sample PHP code:

```php
<?php

use Doctrine\ORM\EntityManagerInterface;

Class ParentResolver implements ResolverInterface
{

	private $em;
	
	public function __construct(EntityManagerInterface $em){
		$this->em = $em;
	}

	private $parent;
	
	public function init($id){
		$this->parent = $this->em->find(ParentEntity::class, $id);
	}
	
	public function getName()
	{
		return $this->parent->getName()
	}
	
	public function getName2()
	{
		return $this->parent->getName();
	}
	
}

Class UserResolver implements ResolverInterface
{
	public function getParent()
	{
		$parent = new ParentResolver($this->em);
		$parent->init(123);
		return $parent;
	}
}

```

I do the following query (I'm not user 123):
```graphql
{
	me{id, name, parent{id, name}}
	user(id: 123){id, name, parent{id, name}}
}
```

GraphQL will load the service `UserResolver` from the container.
Somehow two distinct resolvers are used in order to get different data for `me` and `user(id: 123)`: OK

The field `User.parent` does not give a resolver. So GraphQL, will try to call the `getParent` method of the object returned by method `App\GraphQL\Resolver\UserResolver::me()` and  `App\GraphQL\Resolver\UserResolver::user($args)`: OK

Let's say that this `getParent` method returns an instance of `App\GraphQL\Resolver\ParentResolver`.
This instance is not loaded by GraphQL but with userland code, so it's not part of `Overblog\GraphQLBundle\Resolver\AbstractResolver::$solutions`

If I'm querying `Parent.name2` GraphQL will use the `getName2` of the object returned by the `getParent` method: OK

But if I'm querying `Parent.name` then GraphQL will try to load `App\GraphQL\Resolver\ParentResolver` -(because it's explicitly written in the type definition) to add it to it's solutions, and thus using a different instance than the one coming from the `getParent` method: EXPECTED BEHAVIOR ?

In my case this breaks my code because the `init` method is not called on this new instance: the `parent` property is not defined.

It happens when I define the resolver method, even if useless because GraphQL may find the right one, because I need the `Overblog\GraphQLBundle\Definition\Argument $args` argument.

I've found that using the `value` variable along with `args` as arguments is a way to solve the issue if I replace `$this` with `$value` in my resolver methods.

My questions:
- should I define my resolver classes as non-shared service (https://symfony.com/doc/current/service_container/shared.html) in order to use the container in the `getParent` method instead of manually wiring a new instance of `ParentResolver`?
- should I add the `App\GraphQL\Resolver\ParentResolver` to `Overblog\GraphQLBundle\Resolver\AbstractResolver::$solutions`?
- should I submit a quick-win PR to always pass the `Overblog\GraphQLBundle\Definition\Argument $args` to a resolver method when the `resolve` option is not set in the type definition so GraphQL won't try to load a new instance?
