### ISSUE TITLE
field access seemingly random behavior, data leaked to unauthorized users!

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#387]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12-dev

```yaml
Query:
  type: 'object'
  config:
    fieldsDefaultAccess: '@=isFullyAuthenticated()'
```

On Query fields, I have currently seemingly random behavior, when user is NOT fully authenticated:

Possible outcomes, when I query those fields:
1. error, can not return null on non nullable field
2. proper error response, with "no access"
3. data is returned as if the user is authenticated!

When I modify the config for a field with error (1.) by adding a const "access: false", the query correctly returns "access denied for this field". So it does not have to do with the fact, the field is non-nullable. Otherwise I would get the same error.

When I modify the config for the same field by replacing "false" with "@=isFullyAuthenticated()", it again result in error "can not return null on non nullable field.

It seems like it has something to do with expression evaluation?

A more critical issue is that certain fields return actual data to non-authenticated users!

I do not know what the reason is, but this one is special so I assume its the type of returned value from the expression, which matters. The field is only a "namespace" field:

```yaml
Query:
  [...]
  fieldsDefaultAccess: '@=isFullyAuthenticated()'
  fields:
    thisFieldIsLeaked:
      type: 'FieldType'
      resolve: '@=[]'
```

While the FieldType is an actuall mapped type with resolvers. The data is returned to the client, even if the user is not fully authenticated.

When I add a const "access: false" to this field, I get a proper "access denied" response! So again, the expression seem to influence the behavior in a weird way.

I have tested that the user is actually really not fully authenticated, via debugging, symfony profiler, adding a field which is queries together with the problem-fields returning "resolve: @=isFullyAuthenticated()".

**Comment by akomm** [comment]
I think this is the reason for the data leakage:

https://github.com/overblog/GraphQLBundle/blob/c1c6341534c87c2a2a9b3df6622ac27b47c9c80c/src/Resolver/AccessResolver.php#L62-L68

It assumes all fields of the results are non-virtual properties and available ahead of time. But that is not how the resolve works.

**Comment by mcg-web** [comment]
@akomm I don't really get the issue can you provide a minimal example. If this is a security issue we will BC if needed.

**Comment by mcg-web** [comment]
I think I get it:

It's a normal behaviors that:
- field value is [replaced by null](https://github.com/overblog/GraphQLBundle/blob/master/docs/security/fields-access-control.md#fields-access-control) if `access: '@=isFullyAuthenticated()'` so you field should be null.
- If `access: false` with replace field `resolve` by  [an closure that throw an exception](https://github.com/overblog/GraphQLBundle/blob/master/src/Definition/ConfigProcessor/AclConfigProcessor.php#L28-L30)

**Comment by akomm** [comment]
@mcg-web I know it is replaced with null, but it should not trigger internal error. 

Instead it should provide graphql error. 

It does provide graphql error when I configure `access: false`, why should it not behave the same way with `access: "@=isFullyAuthenticated()"` on the same field?

Maybe you think the expression is still the fieldsDefaultAccess. I was in the narrative context, when I told that `access: false` on the field _directly_ (not fieldsDefaultAccess) does behave different (graphql error), than `@=isFullyAuthenticated()` on the exact same field (internal error). If I was not clear, sorry.

**Comment by akomm** [comment]
Config:
```yaml
Secure:
  type: 'object'
  config:
    fields:
      youShallNotSeeThis: {type: 'String!', resolve: 'top secret data'}
      youAreAuthenticated: {type: 'Boolean!', resolve: '@=isFullyAuthenticated()'}

Query:
  type: 'object'
  config:
    fieldsDefaultAccess: '@=isFullyAuthenticated()'
    fields:
      secureField:
        type: 'Secure'
        resolve: '@=[]'
```
Query:
```graphql
{
  secureField {
    youShallNotSeeThis
    youAreAuthenticated
  }
}
```

Result:
```json
{
  "data": {
    "secureField": {
      "youShallNotSeeThis": "top secret data",
      "youAreAuthenticated": false
    }
  }
}
```

Change config (access: false):
```yaml
Query:
  type: 'object'
  config:
    fieldsDefaultAccess: '@=isFullyAuthenticated()'
    fields:
      secureField:
        access: false
        type: 'Secure'
        resolve: '@=[]'
```
Result (correct, non 500 code http response with graphql error):
```json
{
  "data": {
    "secureField": null
  },
  "extensions": {
    "warnings": [
      {
        "message": "Access denied to this field.",
        "category": "user",
```
