### ISSUE TITLE
[Question] Decoupling root mutation file into separate DDD YAML files

### ISSUE THREAD

**Issue by SebastienTainon** [overblog/GraphQLBundle#409]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11/0.12

Hello,
This is at first a question but maybe also a feature request. From the documentation, we have to declare in the configuration the name of the root mutation file:

```
overblog_graphql:
    definitions:
        schema:
            query: RootQuery
            mutation: RootMutation
```

However, with a big application containing, let's say, 50 or more Relay mutations, the RootMutation.yaml file get heavy and hard to read and organize (hundreds of lines).

Is there a way to decouple it into multiple small YAML mutation files? For example that could be one file for each domain of the application (DDD).

If it's not possible, do you think it could be added to the roadmap or do you have any best practices to handle this a way that is compatible with good development practices on file lines length?

Thanks!

**Comment by mcg-web** [comment]
Hi, you can use decorator to split your RootMutation in multiple files, see type inheritance doc section for more details.

**Comment by SebastienTainon** [comment]
Oh great I didn't know about this, thanks @mcg-web!

For people interested in this, here is the way to do it: you have to create as many GraphQL types as you want, and declare them as decorators. Then, in your RootMutation, you just have to inherit from them so that your RootMutation get their fields in it:

```
UserMutation:
    type: object
    decorator: true
    config:
        fields:
            # your user mutation fields

ProductMutation:
    type: object
    decorator: true
    config:
        fields:
            # your product mutation fields

RootMutation:
    type: object
    inherits: [UserMutation, ProductMutation]
```
