### ISSUE TITLE
Can't set a scalar parameter into GraphQL classes

### ISSUE THREAD

**Issue by tlenclos** [overblog/GraphQLBundle#410]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Version  | 0.11.9

Hi and thanks for your work !

I think I have encountered a bug in the compiler pass. I can't manage to use named parameter for my GraphQL services, they are reset somehow by the bundle.

## Reproduction
in `services.yaml`
```yaml
    App\GraphQL\Mutation\UploadMutation:
        arguments:
            $cardUploadDir: '%card_upload_dir%'
```

in `App\GraphQL\Mutation\UploadMutation`
```php
class UploadMutation implements MutationInterface, AliasedInterface
{
    private $cardUploadDir;

    public function __construct(string $cardUploadDir)
```

I always end up with the exception
```
Cannot autowire service "App\GraphQL\Mutation\UploadMutation": argument "$cardUploadDir" of method "__construct()" is type-hinted "string", you should configure its value explicitly.
```

## Temporary fix for me

Quick and dirty fix for me was to override the process function in my kernel.

```php
    public function process(ContainerBuilder $container)
    {
        $container->getDefinition('App\GraphQL\Mutation\UploadMutation')->setArgument('$cardUploadDir', '%card_upload_dir%');
    }
```

**Comment by mcg-web** [comment]
Hi! thanks for reporting this issue and the reproduction. We'll try to give this a fix quickly.

**Comment by mcg-web** [comment]
Ok I get it, your service is missing the mutation tag
```
    App\GraphQL\Mutation\UploadMutation:
        arguments:
            $cardUploadDir: '%card_upload_dir%'
        tags: ['overblog_graphql.mutation']
```
Also if you register your service using DI no need to implement MutationInterface

**Comment by tlenclos** [comment]
I'm having the same issue with the tag sadly.

**Comment by mcg-web** [comment]
Cna you try to remove `MutationInterface`

**Comment by tlenclos** [comment]
I'm having a weird exception now with

```php
class UploadMutation implements AliasedInterface
{
```

```yaml
    App\GraphQL\Mutation\UploadMutation:
        tags: ['overblog_graphql.mutation']
        arguments:
            $cardUploadDir: '%card_upload_dir%'
```
![image](https://user-images.githubusercontent.com/686101/47438708-4a41b600-d7ab-11e8-8783-f5a0e1ff4df1.png)

**Comment by Sephirothus** [comment]
Hi, what's the status on this bug? I'm using your package and I need to pass entity manager with alternative connection. I'm doing this from services.yaml

        AppBundle\GraphQL\Mutation\UserMutation:
              tags: ['@overblog_graphql.mutation']
              arguments:
                  $em: '@doctrine.orm.user_entity_manager'

 And when I autowire argument in class __constuct, I get default entity manager.

**Comment by mcg-web** [comment]
This bug was not fixed since this could introduce BC, this come from AliasedInterface usage, removed it and defined [your aliases using tags](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/resolver.md#the-service-way).

**Comment by Sephirothus** [comment]
Thanx for quick answer, but it did not help:(
I'll post my whole code, please look at it, maybe I've made a mistake somewhere.

mutation class:
```php
Class UserMutation implements MutationInterface
{
    /**
     * @var EntityManagerInterface
     */
    protected $em;

    public function __construct(EntityManagerInterface $em)
    {
        \Doctrine\Common\Util\Debug::dump($em->getConnection());die; // here I get default connection
        $this->em = $em;
    }

    public function createUser(array $args): User
    {...}
}
```
services.yaml
```yaml
Rozetka\AppBundle\GraphQL\Mutation\UserMutation:
        arguments:
            $em: '@doctrine.orm.user_entity_manager'
        tags: 
            - { name: overblog_graphql.mutation, method: createUser, alias: createUser }
```
Mutation.yaml
```yaml
Mutation:
    type: object
    config:
        fields:
            createUser:
                type: User!
                resolve: '@=mutation("AppBundle\\GraphQL\\Mutation\\UserMutation::createUser", [args["input"]])'
                args:
                    input:
                        type: UserInput!
```

**Comment by mcg-web** [comment]
if you want to use fqcn you must remove alias:

```yaml
AppBundle\GraphQL\Mutation\UserMutation:
        arguments:
            $em: '@doctrine.orm.user_entity_manager'
        tags: 
            - { name: overblog_graphql.mutation, method: createUser }
```

**Comment by Sephirothus** [comment]
Did not helped, still default connection:(
Any thoughts?

**Comment by mcg-web** [comment]
Do you have some wildcard rules in your dependency injection configuration?

**Comment by Sephirothus** [comment]
I get a quick look at project and not found any wildcards

**Comment by mcg-web** [comment]
Can you name your service
```yaml
app.user_mutation:
        class: AppBundle\GraphQL\Mutation\UserMutation:
        arguments:
            $em: '@doctrine.orm.user_entity_manager'
        tags: 
            - { name: overblog_graphql.mutation, method: createUser }
```

what is the output of this CLI?

```
bin/console graphql:debug --category=mutation
```
