### ISSUE TITLE
Pass additional data for type defined in schema.yml

### ISSUE THREAD

**Issue by carere** [overblog/GraphQLBundle#414]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11

Hello :) Thx a lot for this amazing bundle.

I have a question, i would like to add some additional info in my yaml schema:

Exemple:

```
RoleType:
    type: object
    custom_entry: // A custom entry in object scope ?
    config:
        fields:
            id:
                type: ID
            users:
                type: '[UserType]'
                custom_entry: // A custom entry in field scope ? 
            role:
                type: String
            createdAt:
                type: DateTime
            updatedAt:
                type: DateTime
```
So is there any options which allow us to pass custom data ?

I'll explain :) I would like to specify a field amongst the `config.fields` entry, which indicate that it has to be used in order to filter a relation; In my exemple, above, i would like to find a way to indicate that in my field `config.fields.users`, we have to use the field `username` of the `UserType` to filter the relation.

Is that enough clear ?

Best regards ;)
