### ISSUE TITLE
Register `ResolverInterface` and `MutationInterface` for auto configuration

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#439]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes

We are in the process of upgrading our codebase from Symfony 3.3 to Symfony 4 and want to use autowire. We were quite surprised to find out that OverBlogGraphQLBundle has it's own "auto wire" (auto mapping). We disabled that option (`overblog_graphql:    definitions:        auto_mapping: false`) but then found out that the bundle doesn't auto configure the interfaces with the given tags.

By adding the following 2 lines to our own extension, it worked:
```php
$container->registerForAutoconfiguration(ResolverInterface::class)->addTag('overblog_graphql.resolver');
$container->registerForAutoconfiguration(MutationInterface::class)->addTag('overblog_graphql.mutation');
```

Is there a reason this is not added? I can make a PR to add it.

**Comment by mcg-web** [comment]
This could not be added to 0.11 releases since this feature was introduce in Symfony +3.3 and we supports +3.1. For 0.11 we recommends using config file to do the work:

```yaml
services:
    _instanceof:
        GraphQL\Type\Definition\Type:
            tags: ['overblog_graphql.type']
        Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface:
            tags: ['overblog_graphql.resolver']
        Overblog\GraphQLBundle\Definition\Resolver\MutationInterface:
            tags: ['overblog_graphql.mutation']

    App\GraphQL\:
        resource: '../src/GraphQL'
```

 PR are welcome for 0.12-dev (master) version since auto_mapping config was totally removed.
