### ISSUE TITLE
Class 'Overblog\GraphQLBundle\__DEFINITIONS__\RangeFilterType' not found

### ISSUE THREAD

**Issue by VincentClair** [overblog/GraphQLBundle#45]
Hello,

I'm trying to make a query on products with a custom filter type.
Here is the base `Query.types.yml`:
```yaml
Query:
    type: object
    config:
        description: "Product bundle."
        fields:
            getProducts:
                type: "QueryProduct"
                args:
                    filter:
                        description: "Product search filters."
                        type: "ProductFilter"
 ```

My `ProductFilter.types.yml` is defined as an `input-object`:
```yaml
ProductFilter:
    type: input-object
    config:
        description: "Product filters"
        fields:
            categoryIds:
                type: "[Int]"
                description: "Category filter."
            highLight:
                type: "ProductHighLightFilter"
                description: "Highlight product filter."
            ...
            price:
                type: "RangeFilter"
                description: "Product price filter."
            ...
```

 And finally my `RangeFilter.types.yml`, as an `input-object` too:
```yaml
RangeFilter:
    type: input-object
    config:
        description: "Range filter"
        fields:
            min:
                type: "Float"
                description: "Min value."
            max:
                type: "Float"
                description: "Max value."
```

When I run the tests (with Codeception) just after initialize the app (clear cache, install database and load fixtures, create admin user), i get randomly the following error `Class 'Overblog\GraphQLBundle\__DEFINITIONS__\RangeFilterType' not found`.
I get this only for RangerFilter, that is an "inline-object" too.

Have you an idea where the error come from ? Am i using the "inline-object" correctly ?

**Comment by mcg-web** [comment]
Can you try to run your tests in isolated process please (like phpunit)?

**Comment by VincentClair** [comment]
Thanks for your reply. I ran only the crashed test and here is the result:
```
Api Tests (3) -------------------------------------------------------------------------------------------------
Modules: Symfony2, Doctrine2, REST, \Helper\Api
---------------------------------------------------------------------------------------------------------------
Get all manufacturers (Loyalty\ProductBundle\Tests\GraphQL\GraphQLCest::getManufacturers)
Scenario:
* I send post "/auth/login",{"_username":"admin","_password":"admin"}

  [Request headers] []
  [Request] POST /auth/login {"_username":"admin","_password":"admin"}
  [Response] 
  [Headers] {"cache-control":["no-cache"],"x-debug-token":["0d95df"],"Set-Cookie":[{},{}]}
  [Status] 204
* I see response code is 204
* I send get "/",{"query":"query Manufacturers {
    manufacturers {
        id,
        name
    }
}"}
  [Request headers] []
  [Request] GET /?query=query+Manufacturers+%7B%0A++++manufacturers+%7B%0A++++++++id%2C%0A++++++++name%0A++++%7D%0A%7D
PHP Fatal error:  Class 'Overblog\GraphQLBundle\__DEFINITIONS__\RangeFilterType' not found in /var/www/loyalty/product-bundle/var/cache/appTestDebugProjectContainer.php on line 3662

Fatal error: Class 'Overblog\GraphQLBundle\__DEFINITIONS__\RangeFilterType' not found in /var/www/loyalty/product-bundle/var/cache/appTestDebugProjectContainer.php on line 3662
```

RangeFilter seems the only one `input-object` that crash. It is not used by the query, as i try to get manufacturers, but not products.

Here my full query definition:
```
Query:
    type: object
    config:
        description: "Product bundle."
        fields:
            getProducts:
                type: "QueryProduct"
                args:
                    filter:
                        description: "Product search filters."
                        type: "ProductFilter"
                    page:
                        description: "Pagination number."
                        type: "Int"
                    limit:
                        description: "Pagination limit."
                        type: "Int"
                resolve: "@=service('loyalty_product.product_manager').find(user, args['page'], args['limit'], args['filter'])"
            manufacturers:
                type: "[Manufacturer]"
                resolve: "@=service('loyalty_product.manufacturer_manager').find()"
```
