### ISSUE TITLE
resolvers relations nested

### ISSUE THREAD

**Issue by felek000** [overblog/GraphQLBundle#450]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.1.2

I try to get nested data.
I have my Main query 
```
    posts:
        type: "[Post]"
        args:
          id:
            type: "Int"
            description: "Id"
            defaultValue: false
        resolve: "@=resolver('Post', [info, args])"
```

Post type
```
Post:
  type: object
  config:
    description: "Posts"
    fields:
      id:
        type: Int
        description: "Id"
      shortName:
        type: String
        description: "Name"
      tag:
        type: "[Tag]"
        resolve: "@=resolver('Tag', [value, args, context, info])"
        description: "Tag"
        args:
          id:
            type: "Int"
            description: "Id Tag"
            defaultValue: false
```

and my tag

```
Tag:
  type: object
  config:
    description: "Tags"
    fields:
      id:
        type: "Int"
        description: "Id"
      name:
        type: "String"
        description: "Name"
      createDate:
        type: "String"
        description: "Data"
      post:
        type: "[Post]"
        resolve: "@=resolver('Post', [info, args])"
        description: "Posts"
        args:
          id:
            type: "Int"
            description: "Id Post"
            defaultValue: false
```

So now i want to resolve function for tag like so:
If there is parent Post get related tags
If there is an argument for tag get 1 tag by id
If there is no argument for tag get all tags

```
        public function resolve($value,Argument $args,$context, ResolveInfo $info )
        {

//            var_dump($value);die();
            if ($info->path[0] == 'posts') {
                /** @TODO here*/
            } else {
                if ($args['id'] == false) {
                    $tags = $this->entityManager->getRepository(Tag::class)->findAll();
                } else {
                    $tags = [$this->entityManager->getRepository(Tag::class)->find($args['id'])];
                }
            }
            return $tags;
        }
```

This can get my Tag need but i can't access to $value from the post to get related tags, or access to original root id for post to make query for tags.
So my question is how can i get original value to make query for tags, or get post object to get related tags from there.
