### ISSUE TITLE
Union as InputType

### ISSUE THREAD

**Issue by bastos71** [overblog/GraphQLBundle#457]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | v0.11.11

Is there a way to use a Union as Input Object into a Mutation ? 
Apparently it is currently into development : https://github.com/facebook/graphql/pull/395

Here is my case : I've got a union called `EntityUnion` that regroups all my kinds of Types : 

```yaml
EntityUnion:
    type: union
    config:
        types:
            - EntityA
            - EntityB
            - EntityC
```

And I would like to use it, or somemthing similar into a Mutation as a "UnionInput" : 

```yaml
EntityUnionInput:
    type: input-union # or something like that ?
    config:
        types:
            - EntityAInput
            - EntityBInput
            - EntityCInput
```

That way I could configure a mutation like this : 

```yaml
Mutation:
    type: object
    config:
        fields:
            createEntities:
                type: "[EntityGlobalInput]!"
```

Is there a way to do it ? 
Or do I have to find a tricky way ? :/

Thx !

**Comment by mcg-web** [comment]
Hi, this is not possible, this is not part of the specs right now. Union can be use only on output type.  The only trick you can use right now is a custom scalar type.

**Comment by bastos71** [comment]
@mcg-web Thank you for your answer.
But if I use a custom scalar type, all automation taht matches inputs and type mapping would be lost, no ?

I was thinking about another tricky solution : having an InputType that would contain a field for each type contained in my original Union : 

```yaml
EntityGlobalInput:
    type: input-object
    config:
        fields:
            entitiesA: [EntityAInput]
            entitiesB: [EntityBInput]
            entitiesC: [EntityCInput]
```

What do you think ?
