### ISSUE TITLE
Configuration BC break in 0.11.12

### ISSUE THREAD

**Issue by enumag** [overblog/GraphQLBundle#465]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 0.11.12

```yml
overblog_graphql:
    definitions:
        auto_compile: true

```

```
In YamlFileLoader.php line 666:
There is no extension able to load the configuration for "overblog_graphql"
```

If this is intentional then the docs are outdated.
