### ISSUE TITLE
alias fields

### ISSUE THREAD

**Issue by hjanuschka** [overblog/GraphQLBundle#472]
having something like:

```
PresenterImages:
    type: object
    config:
        fields:
            630x616_white_white:
                type: "PresenterImage"
            
```

i get an error that its an illegal field because it starts with an integer.
but the underlying object has those properties, is there a lightwight way (without using custom resolver/transformer)  to alias a field like

```
PresenterImages:
    type: object
    config:
        fields:
            image_630x616_white_white:
                type: "PresenterImage"
                property: "630x616_white_white"
            
```

thx for the great project. ❤️

**Comment by mcg-web** [comment]
@hjanuschka this limitation come from the [GraphQL](https://graphql.github.io/graphql-spec/June2018/#sec-Names) itself. You can use expression language :

```yaml
PresenterImages:
    type: object
    config:
        fields:
            image_630x616_white_white:
                type: "PresenterImage"
                resolve: "@=value.630x616_white_white" # here how this can be done
```

**Comment by hjanuschka** [comment]
@mcg-web many many thx, exactly what i was looking for.

**Comment by hjanuschka** [comment]
`Attempted to load class \"QueryType\" from namespace \"Overblog\\GraphQLBundle\\__DEFINITIONS__\".\nDid you forget a \"use\" statement for another namespace?",`

oops does not seem to work, trying to find a way to debug it

**Comment by hjanuschka** [comment]
`Expected name around position 7 for expression `value.630x616_white_white`.`

**Comment by hjanuschka** [comment]
seems to be not working when integeras at the front, sad, its  a "bad-decision" in the underlying dataobject anyway

**Comment by hjanuschka** [comment]
ok - for the record, ended up like this:



```yaml
PresenterImages:
    type: object
    config:
        fields:
            image_630x616_white_yellow:
                type: "MediaSize"
                resolve: "@=resolver('PropertyResover', [value, '630x616_white_yellow'])"
 
```

Resolver:
```php
<?php
namespace App\GraphQL\Resolver;

use Overblog\GraphQLBundle\Definition\Argument;
use Overblog\GraphQLBundle\Definition\Resolver\AliasedInterface;
use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;

class PropertyResover implements ResolverInterface, AliasedInterface
{



    public function resolve($obj = null, $prop = null)
    {
        return $obj->{$prop};
    }

    public static function getAliases()
    {
        return [
            'resolve' => 'PropertyResover'
        ];
    }
}
```
