### ISSUE TITLE
Setting boolean config value via enviornment variables is not supported

### ISSUE THREAD

**Issue by vroad** [overblog/GraphQLBundle#474]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.12

```yml
overblog_graphql:
    definitions:
        # ...
        auto_compile: "%env(bool:GRAPHQL_AUTO_COMPILATION)%"
```

It's currently not possible to set config values that expects boolean value via env vars, as Symfony's config processor always think that the value is string, not boolean.
To make this work, the fix should be made on the bundle side.

```
Invalid type for path "overblog_graphql.definitions.auto_compile". Expected boolean, but got string.  
```
