### ISSUE TITLE
Using phpdoc as language expression

### ISSUE THREAD

**Issue by sylfabre** [overblog/GraphQLBundle#478]
At AssoConnect, we use the PHPDoc content (class, method and property) as description for GraphQL as we do not want to duplicate code/content.

We have developed a custom language expression `@phpdoc(SomeClass::$someProperty)`.

Would you like a PR for this?

**Comment by Vincz** [comment]
Hi @sylfabre,
I don't really understand what you mean. Could you add more examples ?

**Comment by sylfabre** [comment]
Hi @Vincz 
We use it for description mostly.

For instance with https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/type-system/object.md as an example:
- you probably need to describe the method `character_friends` with `The friends of the character.`
- you don't want to duplicate this description
=> we use `description: @phpdoc('SomeClass::character_friends()')` instead of `description: "The friends of the character."`

**Comment by murtukov** [comment]
@Vincz I think he means something like this: 

```yaml
Query:
    type: object
    config:
        fields:
            author:
                type: "Author"
                description: '@=phpdoc("App\\Entity\\Author")'
                args:
                    id:
                        description: '@=phpdoc("App\\Entity\\Author::$id")'
                        type: "Int"
                     name:
                        description: '@=phpdoc("App\\Entity\\Author::getName()")'
                        type: "String"
                resolve: "@=resolver('Author', [args, info])"
```

@sylfabre If so I find it ok.
