### ISSUE TITLE
Resolve input-object to PHP object

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#479]
It would be nice if I could map input-object's to real PHP objects like I can do with Scalars.

```yaml
MoneyInput:
    type: 'input-object'
    config:
        description: 'Money'
        fields:
            currency:
                type: 'Currency!'
            amount:
                type: 'String!'
```

I want to map this input to `Money\Money` object.
