### ISSUE TITLE
Where do some of the files go?

### ISSUE THREAD

**Issue by Vassyli** [overblog/GraphQLBundle#48]
I'm trying to adapt your symfony bundle to create a graphql interface for our game (lotgd/core). Your readme mentions a bunch of files to get an example ready. Some of them have a filename associated with them while all yml files below "Relay" do not. Where should they go? Is there a fully working example somewhere?

**Comment by mcg-web** [comment]
You free to choice your arborescence for `*.types.yml`. The files can contain many types, or sub directories, since root dir is defined in bundle `Resources/config/graphql`. here a working [example](https://github.com/mcg-web/graphql-symfony-doctrine-sandbox).
You can also choice to add a new root config dir: 
```yaml
overblog_graphql:
    definitions:
        mappings:
            types:
                -
                    type: yml
                    dir: "%kernel.root_dir%/config/access/mapping"
```
