### ISSUE TITLE
Using decorators with graphql

### ISSUE THREAD

**Issue by emr** [overblog/GraphQLBundle#485]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12

Decorators are available with yaml configuration for now in this bundle. But how would be if we use it with graphql schema?

My situation:

We already have an `graphql.schema` file in our project. I want to define each of all of the types as a decorator in this file.

And creating a yaml configuration file to set access rules, resolvers, etc by overwriting them.

So, types are collected in `graphql.schema`, and mappings of these types (configurations, resolvers, access rules, etc) are overwrote in `graphql.yaml` file.

I think this way of use would be very clean.

**Comment by mcg-web** [comment]
Hi @emr, this should already be possible, decorator and inheritance has been introduced in a first place to be used with GraphQL schema language but since it was combining Yaml and GQL we decided to used a more straightforward way `ResolverMap`.

Here how this can be done:

```graphql
type Foo {
  name: String!
}
```

```yaml
FooDecorator:
  decorator: true
  heirs: ["Foo"] # Foo inherited from FooDecorator
  config:
    fields:
      name: {resolve: "John Doe"}
```
