### ISSUE TITLE
ForbiddenOverwriteException with 2 different endpoints

### ISSUE THREAD

**Issue by FabG-CS** [overblog/GraphQLBundle#488]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.12

Hello,
First of all, thank you for all the work done on this bundle.

Then, my question :
I have 2 different endpoints (let's call them "`Endpoint_A`" and "`Endpoint_B`").
I want to have 2 differents GraphQL Schemas (1 schema on 1 endpoint), but they both have a type called "`Client`".
This type "`Client`" can be something totally different in my 2 Schemas; the name is the only common thing between those types in my schemas.
My problem is that I got a `ForbiddenOverwriteException` with this error message : 
> Types ("Client") cannot be overwritten. See inheritance doc section for more details.

I don't understand why I got this message : my 2 endpoints are totally separated, and they have their own graphql schemas in their own directories, so they can have a type with the same name without creating any confusion.

Here is my `config/packages/graphql.yaml` :

```
overblog_graphql:
    definitions:
        schema:
            endpoint_A:
                query: EndpointAQuery
                resolver_maps:
                    - App\Resolver\EndpointAResolverMap
            endpoint_B:
                query: EndpointBQuery
                resolver_maps:
                    - App\Resolver\EndpointBResolverMap
        mappings:
            auto_discover: false
            types:
                endpoint_A:
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types/endpoint_A"
                    suffix: ~
                endpoint_B:
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types/endpoint_B"
                    suffix: ~
```

And here is my Graphql Schemas :

File `endpoint_A.graphql` in directory `config/graphql/types/endpoint_A` :
```
type EndpointAQuery {
    Clients: [Client]!
	Client(id: ID!): Client
}

type Client {
  id: ID!
  name: String!
}
```

File `endpoint_B.graphql` in directory `config/graphql/types/endpoint_B` :
```
type EndpointBQuery {
    Clients: [Client]!
	ClientByFirstName(first_name: String!): Client
}

type Client {
  id: ID!
  first_name: String!
  last_name: String!
}
```

The problem seems to come form `checkTypesDuplication()` in `vendor/overblog/graphql-bundle/src/DependencyInjection/OverblogGraphQLTypesExtension.php`.

So, my question is :
- is it a bug or a voluntary behavior from the bundle ?
- do I do something wrong with my configuration or GraphQl Schemas ? Or maybe what I want to do is not possible ?

Thank you for reading me.

**Comment by mcg-web** [comment]
Hi @FabG-CS,

it would be ambiguous if we could use multiple types with the same name, since all types are compile on the same level and type are not directly attached to a schema.
This is possible in Yaml or Xml since you can use alias to declare your types.

``` yaml
MyClientAlias:
  type: object
  config:
    name: Config

Query:
  type: object
  config:
    fields:
      client: MyClientAlias
```
