### ISSUE TITLE
Invalid defaults for setMaxQueryComplexity and setMaxQueryDepth

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#490]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12-dev

Command example:
`graphql:dump-schema --format=graphql --file=./shared/graphql/api.graphql`

Result:
```
GraphQL\Validator\Rules\QueryDepth::setMaxQueryDepth() must be of the type integer, boolean given, called in [...]/vendor/overblog/graphql-bundle/src/Request/Executor.php on line 109"
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to GraphQL\Validator\Rules\QueryDepth::setMaxQueryDepth() must be of the type integer, boolean given, called in [...]/vendor/overblog/graphql-bundle/src/Request/Executor.php on line 109 in [...]/vendor/webonyx/graphql-php/src/Validator/Rules/QueryDepth.php:102
Stack trace:
#0 [...]/vendor/overblog/graphql-bundle/src/Request/Executor.php(109): GraphQL\Validator\Rules\QueryDepth->setMaxQueryDepth(false)
#1 [...]/var/cache/dev/ContainerYorfBa5/getOverblogGraphql_RequestExecutorService.php(20): Overblog\GraphQLBundle\Request\Executor->setMaxQueryDepth(false)
#2 [...]/var/cache/dev/ContainerYorfBa5/srcApp_KernelDevDebugContainer.php(431): require('/home/andre/dev...')
#3 [...]/var/cache/dev/ContainerYorfBa5/getOverblogGraphql_Command_DumpSchemaService.php(12): ContainerYorfBa5\srcApp_KernelDevDebug in [...]/vendor/webonyx/graphql-php/src/Validator/Rules/QueryDepth.php on line 102
```

Exec: `bin/console config:dump-reference overblog_graphql | grep query_max`
Output:
```
query_max_depth: false
query_max_complexity: false
```

Its populated here: `src/Resources/config/services.yml`:
```yaml
services:
    overblog_graphql.executor.default:
        class: Overblog\GraphQLBundle\Executor\Executor
        public: false

    overblog_graphql.request_executor:
        class: Overblog\GraphQLBundle\Request\Executor
        public: true
        arguments:
            - "@overblog_graphql.executor"
            - "@event_dispatcher"
            - "@overblog_graphql.promise_adapter"
            - "%overblog_graphql.default_resolver%"
        calls:
            - ["setMaxQueryComplexity", ["%overblog_graphql.query_max_complexity%"]]
            - ["setMaxQueryDepth", ["%overblog_graphql.query_max_depth%"]]
```

Generated cache excerpt (*_KernelDevDebugContainer.xml):
```xml
    <parameter key="overblog_graphql.query_max_depth">false</parameter>
    <parameter key="overblog_graphql.query_max_complexity">false</parameter>
```

I do not have those parameters defined in my own config.

Excerpt `\Overblog\GraphQLBundle\DependencyInjection\Configuration`:
```php
    private function securitySection()
    {
        $builder = new TreeBuilder('security');
        /** @var ArrayNodeDefinition $node */
        $node = \method_exists($builder, 'getRootNode') ? $builder->getRootNode() : $builder->root('security');
        $node
            ->addDefaultsIfNotSet()
            ->children()
                ->append($this->securityQuerySection('query_max_depth', QueryDepth::DISABLED))
                ->append($this->securityQuerySection('query_max_complexity', QueryComplexity::DISABLED))
                ->booleanNode('enable_introspection')->defaultTrue()->end()
                ->booleanNode('handle_cors')->defaultFalse()->end()
            ->end()
        ->end();

        return $node;
    }
```

`QueryDepth::DISABLED` equals 0. I think something must be wrong with the **normalization** in `\Overblog\GraphQLBundle\DependencyInjection\Configuration::securityQuerySection`.

The logic there looks odd to me.

**Comment by akomm** [comment]
Btw, the workaround is:
```yaml
parameters:
  overblog_graphql.query_max_complexity: 0
  overblog_graphql.query_max_depth: 0
```

In own config.
