### ISSUE TITLE
[BUG] ID type args always sent to String type

### ISSUE THREAD

**Issue by Ciloe** [overblog/GraphQLBundle#524]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 0.12.0

Upgrade from 0.11.12 to 0.12.0

I have this mutation configuration : 
```yaml
      removeCallAvailability:
        type: "CallAvailabilityRemovedPayload!"
        args:
          id:
            type: "ID!"
            description: "The user call availability id."
        resolve: "@=mutation('removeCallAvailability', [args['id']])"
        description: "Remove a user call availability."
```

And mutation function : 
```php
public function removeCallAvailability(int $id): array
    {
        ...
    }
```

In the last version the `ID` type was automatically transformed to integer whenever a `Int` or a `String` was sent. But now, it will just transformed to `String` at every time.

Expected: 
```graphql
mutation registerCandidate {
  removeCallAvailability(id: 2) {
    success
  }
}
```
This should be a Int

```graphql
mutation registerCandidate {
  removeCallAvailability(id: "2") {
    success
  }
}
```
This should be a String
