### ISSUE TITLE
Decorators do not merge interfaces

### ISSUE THREAD

**Issue by ooflorent** [overblog/GraphQLBundle#543]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

Given the following schema definition:

```yml
InterfaceA:
  type: interface
  config:
    fields:
      a:
        type: String

InterfaceB:
  type: interface
  config:
    fields:
      b:
        type: String

DecoratorA:
  type: object
  decorator: true
  config:
    interfaces:
      - InterfaceA
    fields:
      a:
        type: String

AandB:
  inherits:
    - DecoratorA
  config:
    implements:
      - InterfaceB
    fields:
      b:
        type: String
```

**Problem**

`AandB` does not implement `InterfaceA`.

**Expected behavior**

`AandB` implements `InterfaceA` and `InterfaceB`
