### ISSUE TITLE
Nested resolvers using ResolverMap not called since 0.12 if multiple schemas are defined

### ISSUE THREAD

**Issue by fantomas662** [overblog/GraphQLBundle#547]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 0.12.0, 0.12.1

Defining multiple schemas in v0.12.x prevents "nested resolvers" from being called and the query fails with `Cannot return null for non-nullable field AdminQueries.someField`.

It works again if the profile schema is commented-out.

In v0.11, this works fine.

Query:

```graphql
{
  admin(token: "foo") {
    someField
  }
}
```

Types:

```graphql
type AdminQueryRoot {
    admin(token: String!): AdminQueries!
}

type AdminQueries {
    someField: String!
}

type ProfileQueryRoot {
    dummy: String
}
```

Config:

```yaml
overblog_graphql:
    definitions:
        mappings:
            auto_discover: false
            types:
                -
                    type: graphql
                    dir: '%kernel.project_dir%/config/graphql'
                    suffix: ''

        schema:
            admin:
                query: AdminQueryRoot
                resolver_maps:
                    - app.admin_resolver_map
            profile:
                query: ProfileQueryRoot
                resolver_maps:
                    - app.profile_resolver_map
```

Resolvers:

```php
use Overblog\GraphQLBundle\Resolver\ResolverMap;

class AdminResolverMap extends ResolverMap
{
    private $fieldResolverInvoker;

    public function __construct(callable $fieldResolverInvoker)
    {
        $this->fieldResolverInvoker = $fieldResolverInvoker;
    }

    protected function map()
    {
        return [
            'AdminQueryRoot' => [static::RESOLVE_FIELD => $this->fieldResolverInvoker],
            'AdminQueries' => [static::RESOLVE_FIELD => $this->fieldResolverInvoker],
        ];
    }
}

class ProfileResolverMap extends ResolverMap
{
    private $fieldResolverInvoker;

    public function __construct(callable $fieldResolverInvoker)
    {
        $this->fieldResolverInvoker = $fieldResolverInvoker;
    }

    protected function map()
    {
        return [
            'ProfileQueryRoot' => [static::RESOLVE_FIELD => $this->fieldResolverInvoker],
        ];
    }
}
```

`$fieldResolverInvoker` is a class with `__invoke` that calls another service based on `ResolveInfo`, but that's not important.
