### ISSUE TITLE
Resolver "value" type for array types

### ISSUE THREAD

**Issue by adri** [overblog/GraphQLBundle#55]
Hi! First of all... really great library! Awesome work.

I have a question about the `value` a resolver receives.

On the `User` type definition I have a `contacts` field defined which resolves to an array of `Contact`s:
```yaml
User:
    type: object
            contacts:
                type: "[Contact]"
                description: "The contacts the user can impersonate."
                resolve: '@=resolver("user_contacts", [value, args])'
```

With the `Contact` type definition with a `account` field.
```yaml
Contact:
    type: object
    config:
        fields:
            account:
                type: "Account"
                description: "Account of the contact"
                resolve: '@=resolver("contact_account", [value, args])'
```

When the Account is resolved, the value that is passed to the resolver is the `Contact` casted to an array instead of a `Contact` object. When I resolve the account not via the `contacts` field but via another field of type `Contact` (not `[Contact]`) I get a `Contact` object. 

Any hints why the `value` is an array in the case of the `[Contact]` type?
