### ISSUE TITLE
Is there a way to use additional directories for storing .types.yml files?

### ISSUE THREAD

**Issue by Vassyli** [overblog/GraphQLBundle#56]
See title.

I'd like to extend the functionality of a graphql schema by allowing modules to add their own types. One possibility would be to move the files to AppBundle/resources/graphql/{module}/*.types.yml or link them from there. Doctrine can be configured with additional annotation directories. Is there something similar to this in GraphQLBundle?

**Comment by mcg-web** [comment]
Yes it is possible to defined custom dir just like doctrine.
Here an example of how you can do that using `definitions.mappings` config:

```yaml
overblog_graphql:
    definitions:
        schema:
            query: RootQuery
            mutation: RootMutation
        mappings:
            types:
                -
                    dir: "%kernel.root_dir%/config/my-dir/mapping"
                -
                    type: yml
                    dir: "%kernel.root_dir%/config/access/mapping"
```
