### ISSUE TITLE
Sort fields and arguments

### ISSUE THREAD

**Issue by ooflorent** [overblog/GraphQLBundle#561]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? |  no
| RFC?             | no
| Version/Branch   | n/a

Fields and arguments could be sorted to improve the type readability.

**Comment by murtukov** [comment]
@ooflorent You mean yaml files?

**Comment by akomm** [comment]
@ooflorent is think rather introspection and dump-output (.graphql) ?

**Comment by ooflorent** [comment]
Okay, the idea is this:

```yaml
MyType:
  type: object
  config:
    fields:
      b:
        type: String
      a:
        type: String
```

Should produce this:

```php
new ObjectType([
  'fields' => [
    'a' => …
    'b' => …
  ]
])
```

Instead of this:

```php
new ObjectType([
  'fields' => [
    'b' => …
    'a' => …
  ]
])
```

By having the fields (and arguments) sorted in the type definition, they will be sorted everywhere.
