### ISSUE TITLE
Decorators still do not merge interfaces

### ISSUE THREAD

**Issue by ooflorent** [overblog/GraphQLBundle#565]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

Given the following schema definition:

```yml
A:
  type: interface
  config:
    fields:
      a:
        type: String

AA:
  type: interface
  config:
    fields:
      aa:
        type: String

B:
  type: interface
  config:
    fields:
      b:
        type: String

C:
  type: interface
  config:
    fields:
      c:
        type: String

D:
  type: interface
  config:
    fields:
      d:
        type: String

E:
  type: interface
  config:
    fields:
      e:
        type: String

DecoratorA:
  type: object
  decorator: true
  config:
    interfaces:
      - A
      - AA
    fields:
      a:
        type: String
      aa:
        type: String

DecoratorB:
  type: object
  decorator: true
  config:
    implements:
      - B
    fields:
      b:
        type: String

DecoratorC:
  type: object
  decorator: true
  config:
    implements:
      - C
    fields:
      c:
        type: String

DecoratorD:
  type: object
  decorator: true
  inherits:
    - DecoratorC
  config:
    implements:
      - D
    fields:
      d:
        type: String

ABCDE:
  type: object
  inherits:
    - DecoratorA
    - DecoratorB
    - DecoratorD
  config:
    implements:
      - E
    fields:
      e:
        type: String
```

**Problem**

`ABCDE` does not implement all interfaces.

**Expected behavior**

`ABCDE` implements `A`, `AA`, `B`, `C`, `D` and `E`.
