### ISSUE TITLE
"undefined index ..." in resolve configuration

### ISSUE THREAD

**Issue by estaton** [overblog/GraphQLBundle#566]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12.3

I have a question about passing data to a mutation. I have a configuration like this:
```yaml
ExampleMutation:
  type: object
  config:
    fields:
      example:
        type: Boolean
        resolve: '@=mutation("ExampleMutation", [args["input"]["content"], args["input"]["recipient"]])'
        args:
          input: ExampleMutationInput!

ExampleMutationInput:
  type: input-object
  config:
    fields:
      content:
        type: String!
      recipient:
        type: String
```

As you can see, the recipient field is optional. However, with this configuration, I get the "undefined index recipient" error, no wonder.
```graphql
mutation exampleMutation($content: String!) {
    exmapleMutation(input: {content: $content})
}
```

Is it possible to pass an optional parameter to a mutation in this way or do I have to pass the entire input object and handle the structure in the class?

**Comment by mcg-web** [comment]
When using relay mutation you can use `args["input"]` as expression variable `value` it will return null for any not existing key example `value[recipient]` when not defined. You can also add null as defaultValue to your recipient so your implement will work.

**Comment by murtukov** [comment]
@estaton 

Try this:

```yaml
ExampleMutationInput:
  type: input-object
  config:
    fields:
      content:
        type: String!
      recipient:
        type: String
        defaultValue: null
```
