### ISSUE TITLE
Merging of numeric arrays by inheritance

### ISSUE THREAD

**Issue by murtukov** [overblog/GraphQLBundle#577]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | no
| Version/Branch   | 0.13

Given following decorator:
```yaml
UserInput:
    decorator: true
    config:
        fields:
            username: String!
            password: String!
```

If I inherit this decorator to add 1 more field and change the type of the field `password`:
```yaml
UserCreateInput:
    type: input-object
    inherits: [UserInput]
    config:
        fields:
            password: Int! # overriding the type
            email: String! # adding 1 more field
```

then I get following result as expected:
```yaml
# ...
        fields:
            username: String!
            password: Int!
            email: String!
```
So the existing options are overridden, non-existing options are added.

--------------------------------------------------------------------------------------

But if I try to inherit using validation constraints like this:
```yaml
UserInput:
    decorator: true
    config:
        fields:
            username: String
            password:
                type: String!
                validation:
                    - NotNull: ~
                    - Length: {min: 1, max: 10}
```
```yaml
UserCreateInput:
    type: input-object
    inherits: [UserInput]
    config:
        fields:
            password:
                type: Int!  # overriding type
                validation: # overriding constraints
                    - Json: ~
                    - Length: {min: 50, max: 100}
            email: String!
```

then I get some weird result:
```yaml
# ...
        fields:
            username: String!
            password:
                type: Int!
                validation:
                    - NotNull: ~
                    - Length: {min: 50, max: 100}
            email: String!
```

Expected result:
```yaml
# ...
        fields:
            username: String!
            password:
                type: Int!
                validation:
                    - Json: ~
                    - NotNull: ~
                    - Length: {min: 50, max: 100}
            email: String!
```
So I expect that validation constraints are merged and overriden the same way as other options.
