### ISSUE TITLE
how to define query with parameters by yaml?

### ISSUE THREAD

**Issue by videni** [overblog/GraphQLBundle#581]
```
type Query {
  character(id: ID!): Character
  findHumansByDateOfBirth(years: [Year!]!): [Human!]!
  humans: [Human!]!
  direwolves: [Direwolf!]!
}
```
as I know the yaml config has more features than graphql, what is the correct yaml version? please add it to the doc.

what I did

- [x] Read all documents provided by this bundle
- [x] Read all documents from graphql official website.
- [x]  I have ran the GraphQLBundleDemo

**Comment by videni** [comment]
I see, there is an example 
```
Mutation:
    type: object
    config:
        fields:
            IntroduceShip:
                type: IntroduceShipPayload!
                resolve: "@=mutation('create_ship', [args['input']['shipName'], args['input']['factionId']])"
                args:
                    #using input object type is optional, we use it here to be iso with relay mutation example.
                    input:
                        type: IntroduceShipInput!
```
