### ISSUE TITLE
Compile Error: Cannot declare class XYZ, because the name is already in use

### ISSUE THREAD

**Issue by migo315** [overblog/GraphQLBundle#594]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

As soon as I add one builder to my config.yml ...
```
overblog_graphql:
    definitions:
        # ...
        builders:
            field:
                LocalizedString: 'App\\GraphQL\\Field\\LocalizedStringField'
```

... I get the error message: `Compile Error: Cannot declare class App\GraphQL\Field\LocalizedStringField, because the name is already in use`.

My file under `src/GraphQL/Field/LocalizedStringField.php` looks like this: 

```
<?php

namespace App\GraphQL\Field;

use Overblog\GraphQLBundle\Definition\Builder\MappingInterface;

class LocalizedStringField implements MappingInterface
{
    public function toMappingDefinition(array $config): array
    {
        return [];
    }
}
```

I'm using Symfony 4.3 with autowire and autoconfigure. Does anyone have an idea what causes this?
