### ISSUE TITLE
how to use service in a builder?

### ISSUE THREAD

**Issue by videni** [overblog/GraphQLBundle#595]
I have a custom builder which needs the router service from container, anyway to do this?

```php
class FileLinkFieldDefinition implements MappingInterface
{
    public function toMappingDefinition(array $config): array
    {
        $this->require(['filterName', 'entityAlias', 'route'], $config);

        $route = $config['route'] ;
        $routeParams = [
                'entityAlias' => $config['entityAlias'],
                'filterName' => $config['filterName'],
        ];

        // I found some examples using expression, but I think it is cumbersome, because every time
        // we use service from container, we need to create a expression function. 
        
        // the following way doesn't work which will stop dumping service container.
        return [
            'type' => "String",
            'resolve' => function($value, $serviceContainer) use ($route, $routeParams) {
                $router = $serviceContainer->get('router');

                return $value instanceof AbstractFile? $router->generate($route, $routeParams + ['path' => $value->getPath()]): null;
            },
        ];
    }

    private function require(array $params, $config)
    {
        foreach($params as $param) {
            if(!isset($config[$param]) || !$config[$param]) {
                throw new \Exception(sprintf('%s is required for FileLink', $param));
            }
        }
    }
}
```

**Comment by murtukov** [comment]
Hi @videni 

It's not possible to use services in builders right now. We are currently discussing the ways to rework the builder system of the bundle in the issue #587, which discusses a possibility to make builders as services to allow dependency injection.

**Comment by videni** [comment]
@akomm, Got it , thanks. actually the idea is the same as the `MutationFieldDefinition` class, I did't get it at the first glance.

**Comment by videni** [comment]
hi, @akomm ,   I run into  another issue, can you hep this please? I searched a few hours, but don't find a solution.  I'd like to make the Link resolver more generic, as you can see below.

```
class LinkFieldDefinition implements MappingInterface
{
    public function toMappingDefinition(array $config): array
    {
        $this->require(['route'], $config);

        $route = $config['route'] ?? null;
        $routeParams = $config['parameters'] ?? [];
        $absolute = $config['absolute'] ?? false;

        return [
            'type' => "String",
           // this following like won't work, because routeParams is array. I'd like to keep all route parameters,
         //then evaluate parameter expressions in my LinkResolver, how to pass the array parameters to my Link Resolver?
            'resolve' => sprintf('@=resolver("link", [value, args, %s,  %s, %s])', $route, $routeParams, $absolute)
            ,
        ];
    }
}
```

```
 avatar:
                builder: "Link"
                builderConfig:
                    absolute: true
                    route: pintushi_filtered_image
                    parameters:
                        filterName:  '@=args["filter"]'
                        entityAlias: 'file'
                        filename: '@=value.getPath()'
                args:
                    filter:
                        type: String
                        defaultValue: 'avatar'
```

```
class Link implements ResolverInterface
{
    /** @var UrlGeneratorInterface */
    private $urLGenerator;

    public function __construct(UrlGeneratorInterface $urLGenerator)
    {
        $this->urLGenerator = $urLGenerator;
    }

    public function __invoke($value, $args, string $route = null, array $parameters = [], $absolute = false)
    {
        //@todo evalue expressions in parameters with variables($value, $args);

        return $route ? $this->urLGenerator->generate($route, $parameters, $absolute): null;
    }
}
```

**Comment by akomm** [comment]
It all depends on the whole picture. I would simply pass `args` to the resolver, instead of passing `args `to builder so it then passes it to the resolver.

Then I would think about what the parameters depend on. If they depend on parent value, I would transport the relevant information via the parent value type (for example `AbstractFile` is one you have). I hardly can give you a generic answer to specific problem. You know boundaries of the requirements better than me I guess ^^

**Comment by videni** [comment]
@akomm , seems you didn't understand me well , please look the following configurations. the `paramerters ` part has some expressions,  both `filterName`, `filename` variables are evaluated at runtime, however the `entityAlias` is hardcoded. I need to pass  these parameter into my link resolver, but I didn't find a proper way,  though json_encode might be helpfull, I don't think it is graceful.   I checked the three arguments,  `args`, `info`, `context`, the builderConfig is not included among them. it is only possible if we we can access builderConfig  at run time.

```
 avatar:
                builder: "Link"
                builderConfig:
                    absolute: true
                    route: acme_filtered_image
                    parameters:
                        filterName:  '@=args["filter"]'
                        entityAlias: 'file'
                        filename: '@=value.getPath()'
                args:
                    filter:
                        type: String
                        defaultValue: 'avatar'
```
