### ISSUE TITLE
how to pass configurations to custom type

### ISSUE THREAD

**Issue by videni** [overblog/GraphQLBundle#597]
I'd like to pass a format paramter to DateTimeType

```php
use GraphQL\Type\Definition\ScalarType;

class DateTimeType extends ScalarType
{
    private $format;

    public function __construct($config)
    {
        $this->format = $config['format'] ?? \DateTime::ATOM
    }
    
    /**
     * @param \DateTime $value
     *
     * @return string
     */
    public  function serialize(\DateTime $value)
    {
        return $value->format($this->format);
    }

    /**
     * @param mixed $value
     *
     * @return mixed
     */
    public  function parseValue($value)
    {
        return DateTime::createFromFormat($this->format, $value);
    }

    /**
     * @param Node $valueNode
     *
     * @return string
     */
    public  function parseLiteral($valueNode)
    {
        return DateTime::createFromFormat($this->format, $value);
    }
}
```

```yaml
User:
    type: 'object'
    config:
        fields:
            createdAt:
                type: "DateTime"
                # Error, no config option exists
                config:
                    format: 'yyyy-MM-dd HH:mm:ss'
```

**Comment by videni** [comment]
@mcg-web , I think you point is doing something like this, right?

```
DateTime1:
    type: custom-scalar
    config:
        scalarType: '@=newObject("App\\Type\\DateTime", [ "format" => 'Y-m-d H:i:s'] )'

DateTime2:
    type: custom-scalar
    config:
        scalarType: '@=newObject("App\\Type\\DateTime", [ "format" => 'Y-m-d] )'

```
