### ISSUE TITLE
allow to resolve builderConfig at runtime.

### ISSUE THREAD

**Issue by videni** [overblog/GraphQLBundle#598]
```php
class LinkFieldDefinition implements MappingInterface
{
    public function toMappingDefinition(array $config): array
    {
        $this->require(['route'], $config);

        $route = $config['route'] ?? null;
        $routeParams = $config['parameters'] ?? [];
        $absolute = $config['absolute'] ?? false;

        return [
            'type' => "String",
             // this following like won't work, because routeParams is array. I'd like to keep all route parameters,
             // then evaluate parameter expressions in my LinkResolver, how to pass the array parameters to my Link Resolver? is there a better way than json_encode?
            'resolve' => sprintf('@=resolver("link", [value, args, %s,  %s, %s])', $route, $routeParams, $absolute)
            ,
        ];
    }
}
```

```yml
 avatar:
    builder: "Link"
    builderConfig:
        absolute: true
        route: acme_filtered_image
        parameters:
            filterName: '@=args["filter"]'
            entityAlias: 'file'
            filename: '@=value.getPath()'
    args:
        filter:
            type: String
            defaultValue: 'avatar'
```

```php
class Link implements ResolverInterface
{
    /** @var UrlGeneratorInterface */
    private $urLGenerator;

    public function __construct(UrlGeneratorInterface $urLGenerator)
    {
        $this->urLGenerator = $urLGenerator;
    }

    public function __invoke($value, $args, string $route = null, array $parameters = [], $absolute = false)
    {
        //@todo evaluate expressions in parameters with variables($value, $args);

        return $route ? $this->urLGenerator->generate($route, $parameters, $absolute): null;
    }
}
```
