### ISSUE TITLE
best pratice to make the entry type more organized?

### ISSUE THREAD

**Issue by videni** [overblog/GraphQLBundle#599]
```yaml
overblog_graphql:
    definitions:
        schema:
            admin:
                query: AdminQuery
                mutation: AdminMutation
            shop:
                query: ShopQuery
                mutation: ShopMutation

```

the admin entry contains query and mutation for admin,  in case of this example, API for user, location resources are included,
I have lots of other resources, this file will explode quickly if put these resources here. 
I'd like to keep the user part in the UserBundle, location in LocationBundle, etc. 
since this bundle doesn't allow merging when the root name is duplicated, currently I have no way to do it.

Admin.yaml
```yaml
AdminQuery:
    type: object
    config:
        fields:
        # Location
            locations:
                type: LocationConnection
                resolve: '@=resolver("index", [args, "location", "index", service("request_stack").getCurrentRequest()])'
                args:
                    input: FilterInput
            location:
                type: Location
                resolve: '@=resolver("view", [args,  "location", "view", service("request_stack").getCurrentRequest()])'
                args:
                    code:
                        type: ID!
            createLocationFormSchema:
                type: FormSchema
                resolve: '@=resolver("formSchema", [resolver("form", [args,  "location", "create", service("request_stack").getCurrentRequest()])])'
                args:
                    input:
                        type: LocationInput
            updateLocationFormSchema:
                type: FormSchema
                resolve: '@=resolver("formSchema", [resolver("form", [args,  "location", "update", service("request_stack").getCurrentRequest()])])'
                args:
                    input:
                        type: LocationInput
            provices:
                type: "[SimpleLocationPayload]"
                resolve: '@=resolver("view", [args,  "location", "get_provinces", service("request_stack").getCurrentRequest()])'

            cities:
                type: "[SimpleLocationPayload]"
                resolve: '@=resolver("view", [args,  "location", "get_cities", service("request_stack").getCurrentRequest()])'
                args:
                    provinceCode:
                        type: ID!
            areas:
                type: "[SimpleLocationPayload]"
                resolve: '@=resolver("view", [args,  "location", "get_areas", service("request_stack").getCurrentRequest()])'
                args:
                    cityCode:
                        type: ID!

        # User
            users:
                type: UserConnection
                resolve: '@=resolver("index", [args, "user", "index", service("request_stack").getCurrentRequest()])'
                args:
                    input: FilterInput
            user:
                type: User
                resolve: '@=resolver("view", [args,  "user", "view", service("request_stack").getCurrentRequest()])'
                args:
                    id:
                        type: ID!
            createUserFormSchema:
                type: FormSchema
                resolve: '@=resolver("formSchema", [resolver("form", [args,  "user", "create", service("request_stack").getCurrentRequest()])])'
                args:
                    input:
                        type: CreateUserInput
            updateUserFormSchema:
                type: FormSchema
                resolve: '@=resolver("formSchema", [resolver("form", [args,  "user", "update", service("request_stack").getCurrentRequest()])])'
                args:
                    input:
                        type: UpdateUserInput
            userProfile:
                type: User
                resolve: '@=resolver("view", [args,  "userProfile", "view", service("request_stack").getCurrentRequest()])'
            userProfileFormSchema:
                type: FormSchema
                resolve: '@=resolver("formSchema", [resolver("form", [args,  "userProfile", "update", service("request_stack").getCurrentRequest()])])'
                args:
                    input:
                        type: UserProfileInput
AdminMutation:
    type: object
    config:
        fields:
            # Location
            createLocation:
                builder: "Relay::Mutation"
                builderConfig:
                    inputType: LocationInput
                    payloadType: LocationPayload
                    mutateAndGetPayload: '@=mutation("create", [value, "location", "create", service("request_stack").getCurrentRequest()])'
            updateLocation:
                builder: "Relay::Mutation"
                builderConfig:
                    inputType: LocationInput
                    payloadType: LocationPayload
                    mutateAndGetPayload: '@=mutation("update", [value, "location", "update", service("request_stack").getCurrentRequest()])'
            deleteLocation:
                builder: "Relay::Mutation"
                builderConfig:
                    inputType: DeleteLocationInput
                    payloadType: DeleteLocationPayload
                    mutateAndGetPayload: '@=mutation("delete", [value, "location", "delete", service("request_stack").getCurrentRequest()])'
            # user
            createUser:
                builder: "Relay::Mutation"
                builderConfig:
                    inputType: CreateUserInput
                    payloadType: UserPayload
                    mutateAndGetPayload: '@=mutation("create", [value, "user", "create", service("request_stack").getCurrentRequest()])'
            updateUser:
                builder: "Relay::Mutation"
                builderConfig:
                    inputType: UpdateUserInput
                    payloadType: UserPayload
                    mutateAndGetPayload: '@=mutation("update", [value, "user", "update", service("request_stack").getCurrentRequest()])'
            deleteUser:
                builder: "Relay::Mutation"
                builderConfig:
                    inputType: DeleteUserInput
                    payloadType: DeleteUserPayload
                    mutateAndGetPayload: '@=mutation("delete", [value, "user", "delete", service("request_stack").getCurrentRequest()])'

            # user profile
            updateUserProfile:
                builder: "Relay::Mutation"
                builderConfig:
                    inputType: UserProfileInput
                    payloadType: UserPayload
                    mutateAndGetPayload: '@=mutation("update", [value, "userProfile", "update", service("request_stack").getCurrentRequest()])'

```

**Comment by Asone** [comment]
I faced the same problem. I must admit the documentation is not very handy about this kind of concern, however solving the problem is not that complicated. 

Here is my solution which works well 👍 

First declare the object fields you need in the dispatched file you want. 

Here is an example of one of mine i made for testing which is located in a module in my `src`

```yaml
UserQueries:
    type: object
    config:
        fields:
            getSingleUser:
                type: 'User'
                args:
                    id: 
                        type: 'ID!'
                        description: "User's uuid"
                resolve: "@=resolver('User',[idFromGlobalId(args['id'])])"
            anotherUserQuery:
                type: 'User'
                args:
                    id: 
                        type: 'ID!'
                        description: 'Tata'
                resolve: "@=resolver('User',[idFromGlobalId(args['id'])])"        
```

Then declare inheritance in the main Query like this : 

```yaml
Query:
    type: object
    inherits: [UserQueries]
    config:
        ...
```

Don't forget to declare your subfile, through precise path or through glob in the schema definition through `graphql.yaml` : 

```yaml
overblog_graphql:
    definitions:
        # default_resolver: ''
        schema:
            query: Query
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
                -
                    type: yaml
                    dir: "%kernel.project_dir%/src/**/Types/"
                    suffix: null
```

Enjoy !

N.B : IMHO this should be explicited in the documentation in order to help ease of configuration in the perspective of a consequent schema.
