### ISSUE TITLE
How to apply pagination on big database ?

### ISSUE THREAD

**Issue by VincentClair** [overblog/GraphQLBundle#6]
If I want to apply pagination to some objects, the better way seems to be compatible with Relay.
I have read all specifications about relay, and seen that you have already implemented Connections and Nodes (this last one seems not to be mandatory, but hardly advise).

I think i must use `ConnectionBuilder::connectionFromArraySlice` directly, with the result of a query to my database (with doctrine) and the arguments (first, after, etc.). Must i pass something special like total number of entities ?

I have read too a discussion about adding arguments for filtering/ordering. https://github.com/graphql/graphql-relay-js/issues/20
Have you some advices for this ?

**Comment by mcg-web** [comment]
The builder alone can't answer to this issue. To be possible the logic of calculating the offset and length should be separate from the spliter it self. So you can use this parameter to get your results from db and then the builder could finish the work.

**Comment by VincentClair** [comment]
After a lot of reading, i came with this answer to my problem:
There is two type of pagination:
- "traditional" limit/offset pagination (or page number pagination)
- cursor based pagination, as proposed by Relay specification.

This last one, as said in https://github.com/facebook/relay/issues/540, cursor "pagination model is optimized for infinite scrolling" and data that are heavily update. Think about a list with lot of news comments, etc. like in Facebook. If we scroll, we want to be sure to not repeat the same news: cursors is made for that, to be sure to continue were the last request ended, ever if there is some inserted or delete entries. Its important to noticed that cursor pagination method may apply to an natural ordering and unique field (id, micro timestamp, etc.).

Limit/offset pagination could be a solution when there is no such modifications on entries. It be acceptable if we get the same entry on the next page, because there is a new one during navigation.

So for now, I just implemented the easier solution. Here is an example of an entry point:
```
            users:
                type: "[User]"
                args:
                    limit:
                        description: "Pagination limit."
                        type: "Int"
                    offset:
                        description: "Pagination limit offset."
                        type: "Int"
                    orderBy:
                        description: "Ordering infos"
                        type: "[String]"
                    filterExpression:
                        description: "Filter expression to apply to users"
                        type: "String"
                resolve: "@=service('loyalty_user.user_manager').find(args)"
```

This is a temporary solution, as i must resolve a way to get back the number of results to send to client.
I think the next step is to introduce a UserPaginator object that give that number and the result of users entry point. So, I will not implemented edges and pageinfo in Relay way, to keep a little more simple, dans because I don't need come edges properties. I note that my pagination is applied directly to a "root repository", if it is a good name, and not a collection depending from a root object.

Finally, i have an idea in mind to apply cursor pagination, but it need some heavy tests for performances:
- get all ids from table, applying filters and order by (could be cumbersome)
- cache the result
- apply {first/after} to get a set of ids (could be cumbersome)
- get relevant entries by querying with the set of ids.
Maybe someone has a point of view or a better solution ?

PS: I don't precise the way i made filters (filterExpression) but i really opened to deal with that too.
Thanks of your help
