### ISSUE TITLE
unable to set validation to cascade for "Relay::Mutation" builder

### ISSUE THREAD

**Issue by videni** [overblog/GraphQLBundle#605]
```yaml
updateUser:
    builder: "Relay::Mutation"
#   validation: cascade   // error, no cascade under validation key
    builderConfig:
        inputType: UpdateUserInput
        payloadType: UserPayload
        mutateAndGetPayload: '@=mutation("update", [value, "user", "update"])'

UpdateUserInput:
    type: relay-mutation-input
    config:
        fields:
            id:
                type: ID!
                validation:
                    - NotBlank: ~
```
 
the `ID! ` indicates id field can't be empty, however, it still passed when I submit data like this, that is why I add the NotBlank constraint to id field.

```graphql
{
  "input": {
    "id": ""
  }
}
```

**Comment by murtukov** [comment]
@videni 

It doesn't work because you are trying to apply a cascade validation on the whole field of an `object` type. 

You can only apply `cascade` validation on:
- arguments of `object` types
- fields of `input-object` types

as stated in the documention.

Validation should actually be defined under the `builderConfig` key because it's meant to build a single argument for the `updateUser` field:

```yaml
updateUser:
    builder: "Relay::Mutation"
    builderConfig:
        inputType: UpdateUserInput
        validation: cascade
        payloadType: UserPayload
        mutateAndGetPayload: '@=mutation("update", [value, "user", "update"])'
```
but it's not implemented yet, because we are currently discussing possibilities to fully rework builders (#587), which would also affect `Relay::Mutation` builder.

You don't have to use builders to define your relay mutation. You can write it manually:
```yaml
updateUser:
    resolve: '@=mutation( ... )'
    type: UpdateUserPayload!
    args:
        input:
            type: UpdateUserInput!
            validation: cascade
```
