### ISSUE TITLE
how to pass custom config to custom scalar type?

### ISSUE THREAD

**Issue by videni** [overblog/GraphQLBundle#625]
anyway to pass custom config to custom scalar type?

```
ChannelId:
    type: custom-scalar
    config:
        scalarType: '@=newObject("Acme\\Bundle\\AcmeBundle\\GraphQL\\Type\\Definition\\HashIdType")'
        prefix": '@=param("acme.hash_id.prefix")'
        alias: "channel"
```

```
class HashIdType extends ScalarType
{
    /** @var string */
    public $name = 'HashId';

    /** @var string */
    public $description ='hash id';

    private $hashids;

    public function __construct(array $config = [])
    {
        parent::__construct($config);

        $salt = $config['prefix'] ?? '' + $config['alias'] ?? '';  //I need to use the prefix and alias config here.
    }
}
```
