### ISSUE TITLE
Enhance type mappings to limit to schema(s)

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#644]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | dev-master

Currently you can have multiple schemas. Those schemas will have only types visible, which were used in the schema. This is a good thing. You can also share types between schemas, then they are visible in both. Also nice.

Problems:
The mapping configuration collects everything into a single pool of types, even though at the end not all of them are part of every schema:

1. You have to name your root types differently.
2. You have to name types differently should they have different structure, but preferable same name.

If you think the `public` config solves 2., it does not really. In most cases. It brings in some cumbersome issues with it, like for example having to figure out in which case what schema you actually have and all the conditions have to be passed in somehow, when you want to dump the schema which is visible under those conditions.

Requirements:
1. It should be still possible to share types (call them global)
2. It should be possible to limit types to a schema/schemas

Example illustrating different cases:

```yaml
overblog_graphql:
  schema:
    schemaA:
      query: Query
      mutation: Mutation
    schemaB:
      query: Query
      mutation: Mutation
    schemaC:
      query: Query
      mutation: Mutation
  mappings:
    auto_discover: false
    types:
      - type: yaml
        dir: path/to/global/types
      - type: yaml
        dir: path/to/schemaA/types
        schemas: schemaA
      - type: yaml
        dir: path/to/schemaB/types
        schemas: schemaB
      - types: yaml
        dir: path/to/schemaC/types
        schemas: schemaC
      - types: yaml
        dir: path/to/other/types
        schemas: [schemaA, schemaB]
```
