### ISSUE TITLE
Unrecognized option "validation"

### ISSUE THREAD

**Issue by AliceMakk** [overblog/GraphQLBundle#646]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | the latest

I'm trying to add simple validation in my type ItemBrand, but that throws an error saying `Unrecognized option "validation" under "overblog_graphql_types.CreateItemBrandInput._input_object_config.fields.name". Available options are "defaultValue", "description", "type".`

My ItemBrand.yaml type:
```yaml
ItemBrand:
  type: object
  config:
    description: "An item brand"
    fields:
      id:
        type: "Int!"
        description: "The unique ID of the item brand."
      name:
        type: "String"
        description: "A name of an item brand"

ItemBrandQuery:
  type: object
  config:
      description: "ItemBrand ORM repository"
      fields:
        itemBrand:
          type: "ItemBrand"
          resolve: "@=resolver('ItemBrand', [args])"
          args:
            id:
              description: "Resolves using the item brand id"
              type: "Int"
              
ItemBrandMutation:
  type: object
  config:
    fields:
      createItemBrand:
        type: CreateItemBrandPayload!
        resolve: "@=mutation('create_item_brand', [args['input']['name']])"
        #validation:
        #  link: App\Entity\ItemBrand # targeting the class
        args:
          #using input object type is optional, we use it here to be iso with relay mutation example.
          input:
            type: CreateItemBrandInput!

# ItemBrand
CreateItemBrandPayload:
  type: object
  config:
    fields:
      # id:      
      #   description: "Resolves using the item brand id"
      #   type: "Int"
      itemBrand:
        type: ItemBrand

CreateItemBrandInput:
  type: input-object
  config:
    fields:
      name:
        type: "String!"
        validation:
         - NotBlank: ~
         - Length: { min: 6, max: 32 }
```

What am I doing wrong please?
