### ISSUE TITLE
Validation via Symfony Validator

### ISSUE THREAD

**Issue by AliceMakk** [overblog/GraphQLBundle#650]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13.1

I have Symfony 4.4 and I'm trying to make validation via created Validator:
```php
<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class ItemBrandValidator extends ConstraintValidator
{
    public $message = 'The value "{{ value }}" is bad';

    public function validate($value, Constraint $constraint)
    {
        /* @var $constraint \App\Validator\ItemBrand */

        if (null === $value || '' === $value) {
            return;
        }

        if (strlen($value) > 2) {
            // TODO: implement the validation here
            $this->context->buildViolation($constraint->message)
                ->setParameter('{{ value }}', $value)
                ->addViolation();
        }

    }
}
```

My GraphQL mutation:
```yaml
ItemBrandMutation:
  type: object
  config:
    validation:
      - Callback: [App\Validator\ItemBrandValidator, validate]
    fields:
      createItemBrand:
        type: CreateItemBrandPayload!
        resolve: "@=mutation('create_item_brand', [args['name']])"
        args:
          #using input object type is optional, we use it here to be iso with relay mutation example.
          name:
            type: "String!"
```

Which gives me an error: 
```
Argument 2 passed to App\Validator\ItemBrandValidator::validate() must be an instance of Symfony\Component\Validator\Constraint, instance of Symfony\Component\Validator\Context\ExecutionContext given ...
```

**Comment by murtukov** [comment]
Hi @AliceMakk 

Please tell me more about what are you trying to validate and I'll try to provide you the best way to do it. Are you trying to create your own custom validation constraint?

If so, then you're using it wrong in your yaml config. Instead of typing `Callback` you should use the FQCN of your custom constraint:

```yaml
ItemBrandMutation:
  type: object
  config:
    validation:
      - App\Validator\ItemBrand: ~   # FQCN of your constraint
    fields:
      createItemBrand:
        type: CreateItemBrandPayload!
        resolve: "@=mut('create_item_brand', [args['name']])"
        args:
          name: String!
          # some extra arguments for the demo
          country: String!
          sex: String!
          
```
```php
<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class ItemBrandValidator extends ConstraintValidator
{
    public $message = 'The value "{{ value }}" is bad';

    /**
     * The first argument will be an object of class ValidationNode
     */
    public function validate($object, Constraint $constraint)
    {
        // There is no need to check if $object === null because it
        // will always be an instance of the class 'ValidationNode'
        // if (null === $object) {
        //     return;
        // }

        // You can access all arguments of 'ItemBrandMutation':
        $object->name;
        $object->country;
        $object->sex;

        // Validate whatever you want, e.g. the `name` argument
        if (strlen($object->name) > 2) {
            $this->context->buildViolation($constraint->message)
                ->setParameter('{{ value }}', $object->name)
                ->addViolation();
        }
    }
}
```

**Note**: Don't forget to add the `getTargets` method to your `ItemBrand` class, so that it could be applied to classes (`ValidationNode` in this case):

```php
class ItemBrand extends Constraint
{
    // ...

    public function getTargets()
    {
        return [self::CLASS_CONSTRAINT];
    }
}
```

**Comment by AliceMakk** [comment]
Hey @murtukov , thanks for your short reply as usually :)
Yeah, I would like to have my own validator, don't want to have in the type and also not in the entity. I thought that would be the cleaner way to achieve that by creating my own.

I was just following the [documentation](https://github.com/overblog/GraphQLBundle/blob/master/docs/validation/index.md#input-object) and that causes the error. I've also followed your last steps, but without success. It doesn't call the validator at all, unfortunately.

**Comment by murtukov** [comment]
Please provide me your code (ItemBrandMutation.yaml, ItemBrand.php, ItemBrandValidator.php), because I can't help you without it. There is no way that it's not working if you did everything correctly.

**Comment by AliceMakk** [comment]
Sorry for the late reply.
**ItemBrandMutation.yaml**
```
ItemBrand:
  type: object
  config:
    description: "An item brand"
    fields:
      id:
        type: "Int!"
        description: "The unique ID of the item brand."
      name:
        type: "String"
        description: "A name of an item brand"

ItemBrandQuery:
  type: object
  config:
      description: "ItemBrand ORM repository"
      fields:
        itemBrand:
          type: "ItemBrand"
          resolve: "@=resolver('ItemBrand', [args])"
          args:
            id:
              description: "Resolves using the item brand id"
              type: "Int"

ItemBrandMutation:
  type: object
  config:
    fields:
      createItemBrand:
        type: CreateItemBrandPayload!
        resolve: "@=mutation('create_item_brand', [args['input']['name']])"
        args:
          input:
            type: CreateItemBrandInput!
            validation: cascade

CreateItemBrandPayload:
  type: object
  config:
    fields:
      itemBrand:
        type: ItemBrand

CreateItemBrandInput:
  type: input-object
  config:
    validation:
      - App\Validator\ItemBrandValidator: ~
    fields:
      name:
        type: "String"
```
**ItemBrand.php**
```
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ItemBrandRepository")
 */
class ItemBrand extends Constraint
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message = "ItemBrand.name.notblank")
     * @Assert\Length(
     *     min = 2,
     *     max = 45,
     *     minMessage = "ItemBrand.name.length.min",
     *     maxMessage = "ItemBrand.name.length.max",
     * )
     * @ORM\Column(type="string", length=45)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="Item", mappedBy="brand")
     */
    private $items;

    public function getTargets()
    {
        return [self::CLASS_CONSTRAINT];
    }

    public function __construct() {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setBrand($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
            // set the owning side to null (unless already changed)
            if ($item->getBrand() === $this) {
                $item->setBrand(null);
            }
        }

        return $this;
    }
}
```
**ItemBrandValidator.php**
```
<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;
use Symfony\Component\Validator\ExecutionContext;

class ItemBrandValidator extends ConstraintValidator
{
    public $message = 'The value "{{ value }}" is gopa';

    public function validate($object, Constraint $constraint)
    {
        if (strlen($object->name) > 2) {
            // TODO: implement the validation here
            $this->context->buildViolation($constraint->message)
                ->setParameter('{{ value }}', $object->name)
                ->addViolation();
        }
    }
}
```

**Comment by murtukov** [comment]
@AliceMakk Ok, I see now. We missunderstood each other.

Custom constraints always have 2 classes: a **constraint** class and a **validator** class. They work in pair (see [link](https://symfony.com/doc/current/validation/custom_constraint.html)).
You showed me the **validator** class of your custom constraint with the name `ItemBrandValidator`, so I assumed, that your constraint class is called `ItemBrand` and suggested to put this part into the class `ItemBrand`:

```php
public function getTargets()
{
    return [self::CLASS_CONSTRAINT];
}
```

But as I can see now, your entity is also called `ItemBrand` and you made changes to the entity, which is wrong.

So eventually you should have following classes:
- `ItemBrand` and `ItemBrandValidator` for your custom constraint
- `ItemBrand` entity

You can rename the constraint class `ItemBrand` into `ItemBrandConstraint` to avoid ambiguity with the entity. But it's not conventional, because usually constraint classes don't have the suffix `Constraint`.

Then make following:
1) Your entity should NOT extend the `Constraint` class.
2) Remove from your entity the following code and put it into `ItemBrandConstraint` class (or into `ItemBrand` constraint class if you didn't rename it):
```php
public function getTargets()
{
    return [self::CLASS_CONSTRAINT];
}
```
3) In your yaml config you should use your **constraint** class, not the **validator** class:
```yaml
CreateItemBrandInput:
  type: input-object
  config:
    validation:
      - App\Validator\ItemBrandConstraint: ~
    fields:
      name:
        type: "String"
```

Now it should work. 

Btw I see you have validation annotations in your entity. Didn't you want to remove all the validation from your entities?

P. S. I have updated the validation docs, mainly the [How does it work?](https://github.com/overblog/GraphQLBundle/blob/master/docs/validation/index.md#how-does-it-work) section. Later I will add some usefull recipes, hope it will help you and other users.
