### ISSUE TITLE
ALTAIR GraphQL Client - Old version of GraphQL

### ISSUE THREAD

**Issue by ktrzos** [overblog/GraphQLBundle#651]
| Q                | A
| ---------------- | -----
| Bug report?      | ~~yes~~/no
| Feature request? | ~~yes~~/no
| BC Break report? | ~~yes~~/no
| RFC?             | ~~yes~~/no
| Version/Branch   | 0.13.1

Hi! I'm using ALTAIR GraphQL Client extension for Firefox/Chrome browsers. Every time when I refresh endpoint docs, I got this message:

![Selection_006](https://user-images.githubusercontent.com/14212721/74100371-7616b580-4b2e-11ea-82d9-404ecea97bd5.png)

Are there any plans to upgrade GraphQL version in this bundle? Or maybe there is any way of removing this irritating message? Thanks in advance for any answers :)!

**Comment by mcg-web** [comment]
hi @ktrzos, are the lib `webonyx/graphql-php` up to date? You can try first updating it with composer if this is not the case. Since the bundle is just a Symfony implementation of this lib, you should probably open this issue directly in  `webonyx/graphql-php` if this doesn't solve your issue.

**Comment by ktrzos** [comment]
@mcg-web 

The `webonyx/graphql-php` was up to date. This issue is somehow related with routes. 

```yml
overblog_graphql_endpoint:
  resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"
  prefix: /gql
```

While using above config, I couldn't send requests via `$_POST` method. For those type of requests, server was returning 404 code. _[also, GraphiQL for Chrome didn't want to work]_ But while using `$_GET`, ALTAIR client was sending 3 requests when I wanted to refresh schema documentation. The interesting fact was, that the 1st of those requests was returned with 502 code from my local server (??).

![Selection_006](https://user-images.githubusercontent.com/14212721/74101416-dd863280-4b39-11ea-9f53-7d0af14d66ed.png)

Everything started to work fine after modifying above route to this:

```yml
overblog_graphql_endpoint:defaults:
  path: /gql
  requirements:
    _method:  POST
  defaults:
    _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
    _format: "json"
```

It now accepts both `$_POST` and `$_GET` requests. The GraphiQL extension is also working fine. The same thing is for `graphql-codegen` which was not working previously for the 1st routing config.

Maybe I've done a mistake? Did I use proper routing configuration?
