### ISSUE TITLE
Unable to split query configuration into several files

### ISSUE THREAD

**Issue by kix** [overblog/GraphQLBundle#658]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13.0

` Overblog\GraphQLBundle\DependencyInjection\Compiler\ConfigParserPass->checkTypesDuplication()` disallows splitting queries and mutations into several files.

Imagine I have quite a lot of queries and mutations. The thing that would quite help me manage that is splitting: queries and mutations for `x` are in `types/x.yaml` looking something like:

```yaml
Query:
    type: object
    config:
        description: "Public queries"
        fields:
            listXs: ...
            showSingleX: ...
```

However I'm currently unable to do so since the parser pass does not merge the configs (and maybe check for conflicts there), but instead treats overlapping keys as conflicts.

I see #169 has been opened but looks like it has gotten irrelevant to its author.

**Comment by mcg-web** [comment]
You should use [decorators](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/type-inheritance.md) to split your fields here is an example of how this can be done:

```yaml
Mutation:
    type: object
    inherits: [ProjectMutations, StageMutations]
```

```yaml
ProjectMutations:
    decorator: true
    config:
        fields:
            createProject:
#...
```

```yaml
StageMutations:
    decorator: true
    config:
        fields:
            createStage:
#...
```

this will create a type `Mutation` with two fields `createProject` and `createStage`.
