### ISSUE TITLE
FieldAccess works not as expected

### ISSUE THREAD

**Issue by LrMiLoef** [overblog/GraphQLBundle#673]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? |no

Hey,
i'd like to make a field accessible for a small group of users.
For that i added this into my services.yaml:

```yaml
App\Service\UserService:
    public: false
    tags:
      - { name: 'overblog_graphql.global_variable', alias: 'user_service' }
```

My typeDefinition looks like that:
```yaml
Item:
  type: object
  config:
    fields:
      id:
        type: "String!"
      type:
        type: "String!"
      publishDate:
        type: "DateTime"
      author:
        type: "Person"
        access: "@=service('user_service').hasAccess()"
```

Now i have 2 issues:

1.) `access`-Field will be ignored completely when type is `Person`. How can i use `access` when the fieldtype is an other custom type?

2.) When adding `access`-Field to `publishDate`, for example, i'll get an error that the service `user_service` cannot be found. Is there something missing in `services.yaml` or why can't symfony resolve the alias?
