### ISSUE TITLE
Value on Enum type is ignored in YML

### ISSUE THREAD

**Issue by mcrawford-dayspring** [overblog/GraphQLBundle#676]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12.7

It seems like the "value" of an enum is ignored, and only the name is used.

If I have this YML definition:

```yaml
TestEnum:
  type: enum
  config:
    values:
      TEST:
        value: 'just a test'
      ANOTHER: 'another test'
```

then this is what will get returned in the schema introspection query:

```json
{
    "kind": "ENUM",
    "name": "TestEnum",
    "description": null,
    "fields": null,
    "inputFields": null,
    "interfaces": null,
    "enumValues": [
              {
                "name": "TEST",
                "description": null,
                "isDeprecated": false,
                "deprecationReason": null
              },
              {
                "name": "ANOTHER",
                "description": null,
                "isDeprecated": false,
                "deprecationReason": null
              }
    ],
    "possibleTypes": null
}
```

I would expect to see a `"value": "just a test"` element in there.
