### ISSUE TITLE
How I can understand what fields requests

### ISSUE THREAD

**Issue by des1roer** [overblog/GraphQLBundle#677]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | x.y.z

how to understand in the code which fields the frontend requests

**Comment by murtukov** [comment]
@des1roer you can inject in any of your resolvers a ReolveInfo parameter

```yaml
Query:
    type: object
    config:
        fields:
            getSomething:
                type: String
                resolve: "@=res('my_resolver', [args, info])"
# ...
```

```py
public function myResolver(Argument $args, ResolveInfo $info) {
    # Use $info to get information about the queried fields
}
```
