### ISSUE TITLE
Resolving hasSomething / isSomething methods not working

### ISSUE THREAD

**Issue by ktrzos** [overblog/GraphQLBundle#679]
I have this entity:

```php
class User {
  private $deleted;

  public function isDeleted(): bool {
    return $this->deleted;
  }
}
```

and its configuration:

```yml
Query:
  type: object
  config:
    fields:
      user:
        type: 'User!'
        args:
          id:
            type: 'Int!'
        resolve: "@=resolver('User', [args['id']])"

User:
  type: object
  config:
    fields:
      deleted:
        type: "Boolean!"
```

While executing this query:

```
{
  user(id: 1) {
    deleted
  }
}
```

I got this message:

> Cannot return null for non-nullable field User.deleted.

My resolver looks simply like this:

```php
class UserResolver implements ResolverInterface, AliasedInterface
{
    public function resolve(int $id): User
    {
        $user = $this->userRepository->find($id);

        if (null === $user) {
            throw new UserError('Error.');
        }

        return $user;
    }

    public static function getAliases(): array
    {
        return [
            'resolve' => 'User',
        ];
    }
}
```

It works when renaming getter from `isDeleted` to `getDeleted`.
Why `isSomething` or `hasSomething` methods does not work?

I even tried to set `isDeleted` field in the configuration instead of `deleted`, but it still doesn't help.
