### ISSUE TITLE
How to create a "int -> entity" scalar

### ISSUE THREAD

**Issue by ktrzos** [overblog/GraphQLBundle#683]
I want to create an input scalar type in my schema. It should take an integer on input and in internal use it would return an entity with this integer as its ID. If particular entity will not exist, error should appear in GraphQL client.

The problem is, that scalar methods are static, and I cannot access entity repository or anything in dependency container. On [webonyx](https://webonyx.github.io/graphql-php/type-system/scalar-types/) those methods aren't static. What can be done here?

**Comment by murtukov** [comment]
Hi @ktrzos.

Regardless of which configuration method you choose (yaml, annotations, graphql etc.), this bundle eventually just generates for you webonyx types, which you can find under the path (unless changed): 
`var/cache/dev/overblog/graphql-bundle/__definitions__`
All generated types are services.

This means that you can create your custom webonyx type manually (non-generated type). To do this, simply create your own service e.g.:

```php
<?php

namespace App\GraphQL\Type;

use App\MyRepository;
use GraphQL\Error\Error;
use GraphQL\Language\AST\IntValueNode;
use Overblog\GraphQLBundle\Definition\ConfigProcessor;
use Overblog\GraphQLBundle\Definition\LazyConfig;
use Overblog\GraphQLBundle\Definition\Type\CustomScalarType;

final class EntityType extends CustomScalarType
{
    const NAME = 'Entity';

    /**
     * You can now inject any service you want. $configProcessor is mandatory
     */
    public function __construct(ConfigProcessor $configProcessor, MyRepository $repository)
    {
        $configLoader = function() use ($repository) {
            return [
                'name' => self::NAME,
                'description' => "Converts id to entity",
                'serialize' => function ($user) use ($repository) {
                    // Convert entity to int
                    return $user->getId();
                },
                'parseValue' => function ($id) use ($repository) {
                    // Convert id to entity
                    return $repository->findUserById($id);
                },
                'parseLiteral' => function ($valueNode) use ($repository) {
                    // Accept only integer values
                    if (!$valueNode instanceof IntValueNode) {
                        throw new Error('Query error: Can only parse integers, got: ' . $valueNode->kind, [$valueNode]);
                    }

                    // Convert id to entity
                    return $repository->findUserById($valueNode->value);
                },
            ];
        };

        // This lines are required
        $config = $configProcessor->process(LazyConfig::create($configLoader))->load();
        parent::__construct($config);
    }
}
```
Tag your service with `overblog_graphql.type` and give your type a name with `alias`:
```yaml
services:
    App\GraphQL\Type\EntityType:
        tags:
            - { name: overblog_graphql.type, alias: Entity }

# If you don't use autoconfiguration, you have to inject arguments manually:
# services:
#    App\GraphQL\Type\EntityType:
#        arguments:
#            - '@Overblog\GraphQLBundle\Definition\ConfigProcessor'
#            - '@App\MyRepository'
#        tags:
#            - { name: overblog_graphql.type, alias: Entity }
```

Then you can use your new type as input:
```yaml
Mutation:
    type: object
    config:
        fields:
            removeUser:
                type: String
                resolve: "@=mut('user/remove', [args])"
                args:
                    user: "Entity!"
```
Resolver
```php
<?php

declare(strict_types=1);

namespace App\GraphQL\Mutation;

use Overblog\GraphQLBundle\Definition\ArgumentInterface;
use Overblog\GraphQLBundle\Definition\Resolver\AliasedInterface;
use Overblog\GraphQLBundle\Definition\Resolver\MutationInterface;

class DefaultMutation implements MutationInterface, AliasedInterface
{
    public function removeUser(ArgumentInterface $args)
    {
        $user = $args['user'];

        // Do something with user

        return 'Ok!';
    }

    public static function getAliases(): array
    {
        return [
            'removeUser' => 'user/remove'
        ];
    }
}
```
