### ISSUE TITLE
Allow entity id scalar generation

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#694]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 1.0.0

I'm currently working on a pretty big corporate application. So I have many entities with cruds, forms, etc... So a lot of code is "automatic" and it's great. I know feel the same need expressed here : https://github.com/overblog/GraphQLBundle/issues/683

The use case is quite simple. When I create a form for an entity (and I have many), I describe my Input with foreign key id as Int and I have to convert them back to entities in my resolver. 
For example:

```yaml
HeroInput:
    type: input-object
    config:
        fields:
            name:
                type: "String!"
           partnerId:
                type: "Int"
````

And in my resolver, I have to do something like : 
```php
function resolve($input) {
   $hero = new Hero();
   $hero->setName($input['name']);
   $partner = $this->getEntityManager()->getRepository(Hero::class)->find($input['partnerId']);
   $hero->setPartner($partner);
}
```
So, I have to be specific for each different entity (one resolver by entity), preventing me from having a single generic resolve function. 

If we could automatically generate scalars to represent each entity, we could save a lot of time. 
The Input would become:
```yaml
HeroInput:
    type: input-object
    config:
        fields:
            name:
                type: "String!"
           partnerId:
                type: "HeroId"
````
and the resolver :
```php
function resolve($input) {
   $hero = new Hero();
   $hero->setName($input['name']);
   $hero->setPartner($input['partner']);
}
```
and the generated scalar would simply be a id to entity converter like https://github.com/overblog/GraphQLBundle/issues/683#issuecomment-650576014 for example.

The option could be opt in by simply adding a "generateScalar" boolean option on the `@GQL\Type` annotation. I'm not sure how we could implement this out of annotation. 

Let me know what you think.

**Comment by murtukov** [comment]
Hi @Vincz,

I am already working for couple of months on a feature called **Hydrator**. It will basically allow you to assotiate a **model** class to an `input-object` type and when a request comes, the model will be populated with data. It is similar to what you created (called `ArgumentsTransformer` if i am correct), but it should be more comprehensive and flexible. One of the **Hydrator**'s features will be ability to apply converters to any field and this is, I believe, what you need right now. I'll show you an example:

```yaml
Mutation:
    type: object
    config:
        fields:
            createHero:
                resolve: "@=mut('create_hero', [models])"
                args:
                    input: HeroInput!

HeroInput:
    type: input-object
    model: App\Model\HeroInput
    config:
        fields:
            name:
                type: "String!"
           partnerId:
                type: "HeroId"
```
Model:
```php
class Hero
{
    public string $name;

    /*
     * @Hydrator\Field("parentId") - this only required because fields have different names
     * @Converter\Entity
     */
    public Hero $parent;
}
```
Resolver:
```php
public function resolve(Models $models)
{
    $heroInput = $models->get('input')
    // or
    $heroInput = $model->input;
}
```
So this eventually doesn't change args, but introduces `models` variable (args are left untouched), which is a container for all models (there can be many, flat or nested). Now this is a simple example, but it will also allow you to define your own custom converters, configure hydration strategy for your models (for example, when you perform an update action, you usually want to retreive the data from DB first and then replace it with request data). It will also catch convertion errors and map them as validation violations

There will be some integrated converters, like `Entity`, `Service`, `Instance` (e.g. to convert strings to DateTime objects) etc. and if it's not enough, you can define your services and use them as custom converters. 

Hydrator will also be highly integrated with the Validator feature. 

Is this what would help you in your situation?
