### ISSUE TITLE
Allow more control over config processing

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#702]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 1.0.0

At the moment, all the config processing classes are hardcoded and static stuff : The processor, the various parsers, etc...
It's then impossible to extend them or modify the behaviour for a specific project.
It could be great to be able to change this classes if needed. 
Also, is there a specific reason why all this classes use static methods ?

We could add all this classes definitions as configuration offering the ability to change them.

For example:

```yaml
overblog_graphql:
    parsers:
        annotations:  App\GraphQL\Parsers\AnnotationParser
        yaml: App\GraphQL\Parsers\YamlParser
```
