### ISSUE TITLE
v0.13.3 returns null on all fields

### ISSUE THREAD

**Issue by hjanuschka** [overblog/GraphQLBundle#716]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |  no
| BC Break report? | yes
| Version/Branch   | 0.13.3

i upgraded from v0.12.10 to v0.13.3

and my properties do not resolve anymore, in my resolver i return "objects" - and in the yaml i map them.
with v0.12.10 - it works - like the yaml `id` property with type int returns $obj->id

with v.13.3.3 it returns null

simplified sample
object:

```php
<?php
class MyObject {
   function __get($name) {
       return $this->payload->$name;
   }
   function __construct($id) {
        $this->payload = (object)["id" => $id];
   }
}

```

Resolver:

```php
<?php

namespace App\GraphQL\Resolver;
use Overblog\GraphQLBundle\Definition\Resolver\AliasedInterface;
use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;

class PostResolver implements ResolverInterface, AliasedInterface {
    public function resolve($id) {
        $obj = new MyObject($id);
        return $obj;
    }

    public static function getAliases(): array {
        return [
            'resolve' => 'Post',
        ];
    }
}

```

type yaml.
```yaml
Post:
  type: object
  config:
    description: "Post"
    fields:
      data:
        resolve: "@=resolver('Post', [value.id])"
        type: PostObject


PostObject:
  type: object
  config:
    description: "Article"
    fields:
      id:
        type: "Int"
        description: "the unique id of the post"

```

query:
```yaml
post:
        type: "Post"
        resolve: "@=resolver('Post', [args['id']])"
        args:
          id:
            description: "the article id"
            type: "Int"
```

gql query:

```yaml
post(id: 123) {
  data {
    id
  }
}
```
(returns 123 in v0.12.xx and `null` in v0.13.3)

any idea?

**Comment by hjanuschka** [comment]
ok - i figured it out, with v0.13.3 FieldResolver is used.


my real object, (edited above) - uses magic `__get(XXX)`  - and `isset()`  doesn't trigger `__get` .

fix: i implemented `__isset` which should be used for this case.

**Comment by hjanuschka** [comment]
introducing the `__isset`  method in my code introduced way tooo many errors - any ideas, what would be a good approach?

**Comment by mavimo** [comment]
@hjanuschka maybe you can override the FieldResolver service and create your own resolver that will handle your specific need?

**Comment by murtukov** [comment]
@hjanuschka As far as I know, in the version 0.12 we used [PropertyAccess](https://symfony.com/doc/current/components/property_access.html) component to automatically map fields of your returned objects (MyObject in your example). However this solution was slow an was replaced with another, more efficient one. It seems like the new solution cannot detect fields created dynamically (ignores `__get` method). You can create your own field resolver:

1. Define a field resolver for your type:
```yaml
PostObject:
  type: object
  config:
    resolveField: '@=resolver("Post/resolveField", [value, info])'
    description: "Article"
    fields:
      id:
        type: "Int"
        description: "the unique id of the post"
```
2. Add alias and the method:
```php
class PostResolver implements ResolverInterface, AliasedInterface {
    public function resolve($id) {
        $obj = new MyObject($id);
        return $obj;
    }

    public function fieldResolver(MyObject $object, ResolveInfo $info)
    {
        switch($info->fieldName) {
            case 'description':
                // using getter
                return $object->getDescription();

            case 'id':
                // using direct field access
                return $object->id;

            default:
                // Use PropertyAccess by default, if you want
                return $this->propertyAccessor->getValue($object, $info->fieldName);
        }
    }

    public static function getAliases(): array {
        return [
            'resolve' => 'Post',
            'fieldResolver' => 'Post/resolveField',
        ];
    }
}
```
The method `fieldResolver` will be called for each field of your returned object.
