### ISSUE TITLE
How to pass args to sub objects?

### ISSUE THREAD

**Issue by jalso** [overblog/GraphQLBundle#74]
Hi!

I am using GraphQL to query a list of objects ("sport"). The query has a timestamp input argument "date". This works fine for the main sport object that resolves correctly. However, I need to figure out how to pass the date argument down to the matchcounts resolver. My actual code not works, the args input in resolveMatchCounts method is allways empty. I am a newbie about GraphQL... Thank You.

```javascript
query sports {
  sports (date: 1477785600){
    id
    name
    matchCounts {
        finished
        scheduled
      }
  }
}


```

Query.types.yml:

```yaml
Query:
    type: object
    config:
        fields:
            sports:
                  type: "[Sport]"
                  args:
                      date:
                          description: "timestamp"
                          type: "Int"
                  resolve: "@=resolver('sport_sports', [args])"
```
Sport.type.yml:

```yaml
Sport:
    type: object
    config:
        description: "Sport"
        fields:
            id:
                type: "String"
                description: "The id of the sport."
            name:
                type: "String"
                description: "The name of the sport."
            matchCounts:
                type: "MatchCounts"
                description: "match counts for this sport"
                resolve: "@=resolver('sport_matchcounts', [value, args])"
```
MatchCounts.type.yml:
```yaml
MatchCounts:
    type: object
    config:
        description: "MatchCounts"
        fields:
            finished:
                type: "Int"
                description: "Finished"
            scheduled:
                type: "Int"
                description: "scheduled count."
```

Services.yml:
```yaml
    my.graph.resolver.sports:
        class: ApiBundle\GraphQL\Resolver\SportsResolver
        arguments:
            - "@overblog_graphql.type_resolver"
        tags:
            - { name: overblog_graphql.resolver, alias: "sport_sports", method: "resolveSports" }
            - { name: overblog_graphql.resolver, alias: "sport_matchcounts", method: "resolveMatchCounts" }
 ```

SportsResolver.php:
```php

public function resolveSports($args)
    {
        $timestamp = isset($args['date']) ? (int)$args['date'] : time();
        //args is not empty

        $sportModel = $this->container->get('model.sport.sports');
        $data = $sportModel->getSportsData(['timestamp' => $timestamp]);
        
      return $data;
    }


 public function resolveMatchCounts($sport, $args)
    {
      
        //$args is empty :(
        //print_r($args->getRawArguments());
        $timestamp = isset($args['date']) ? (int)$args['date'] : time();

        $sportModel = $this->container->get('model.sport.sports');
        $data = $sportModel->getSportMatchCount(['timestamp' => $timestamp], $sport);
        return $data;
    }
```
