### ISSUE TITLE
Compiled PHP class syntax error for exact length validation

### ISSUE THREAD

**Issue by werdlv** [overblog/GraphQLBundle#744]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | v0.13.3

```yaml
country:
  type: String!
  validation:
    - Length: { min: 2, max: 3 }
```
Running command `graphql:compile -n` given example works as expected.

Here is how resulting PHP class looks like.
![image](https://user-images.githubusercontent.com/1607778/90404447-1421a480-e0ab-11ea-86ca-2e142312d7c4.png)

```yaml
country:
  type: String!
  validation:
    - Length: { min: 2, max: 2 }
```
This one does not - compiled PHP class is missing a comma after min and therefore the request fails with PHP syntax error.

![image](https://user-images.githubusercontent.com/1607778/90404350-f6543f80-e0aa-11ea-8a0a-331f98c20feb.png)
