### ISSUE TITLE
How to get parent of parent

### ISSUE THREAD

**Issue by Fivedark** [overblog/GraphQLBundle#757]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12.6

Is it possible to get the parent of the value inside a resolver? 

Here is a minified example:

The query:
```yaml
products:
    type: "[Product]"
    resolve: "@=resolver('products', [info])"
```
The `products` resolver loads all products. I removed args for this example to keep it small and clean.

Product type:
```yaml
Product:
  type: object
  config:
    fields:
      id:
        type: Int
      slug:
        type: String
      defaultView:
        type: "View"
        resolve: "@=resolver('productDefaultView', [value, info])"
```
The `productDefaultView` resolver uses a dataloader to solve the n+1 issue.

View type:
```yaml
View:
  type: object
  config:
    fields:
      id:
        type: Int
      slug:
        type: String
      imageUrl:
        type: String
        resolve: "@=resolver('productViewImageUrl', [value, info])"
```

The `productViewImage` resolver should build an Url based on the unique slugs of the View **and the Product**. But the resolver only get the View object (value). 

```php
    public function resolveProductViewImageUrl(View $view, ResolveInfo $info): string
    {
        $path = $info->path;

        return $this->imageService->getProductViewImageUrl(
            $product->getSlug(),
            $view->getSlug()
        );
    }
```

`$path` will contain an array like this:
```php
[
   'products',
   0,
   'defaultView',
   'imageUrl'
]
```

How can the `productViewImageUrl` resolver get also the product object ($product)? 
It corresponds to the `0` in the path array. Is there a way to get all the objects up this path, also on more nested relations?

**Comment by murtukov** [comment]
Hi @Fivedark,

use the `context` variable. You can think of it as a bag that every resolver has access to.
Just add any value to te context variable and retreive that value from any resolver down the path:

```yaml
products:
    type: "[Product]"
    resolve: "@=resolver('products', [context])"
```
```php
public function products($context): string
{
    // add values into $context
}
