### ISSUE TITLE
Property arguments/modifiers

### ISSUE THREAD

**Issue by inwaar** [overblog/GraphQLBundle#766]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | last

Hi, I didn't find it in the documentation.
E.g.:

```graphql
query GetPerson {
  people(id: "7") {
    firstName
    lastName
    avatar(size: LARGE)
  }
}
```
How can I get the `size` modifier in a resolver function?
Additionally if a property is a custom scalar say:

```graphql
query GetPerson {
  people(id: "7") {
    firstName
    lastName
    registerDate(format: 'Y-m-d')
  }
}
```

How can I get the `format` value in the custom scalar class `Date`?

**Comment by inwaar** [comment]
Another question: how such arguments can be defined in a schema by yaml config files?

**Comment by murtukov** [comment]
```graphql
query GetPerson {
  people(id: "7") {
    firstName
    lastName
    avatar(size: LARGE)
  }
}
```

**Comment by murtukov** [comment]
Hi @inwaar,

Arguments are available only in the corresponding resolver of the field. You defined arguments `id` and `size` separately, so the `id` arg will be accessible only in the resolver defined for the `person` field and the `size` arg will be accessible in the resolver defined for the `avatar` field.

You have 2 options: either define both arguments 'together' or create 2 resolvers.

```graphql
# Both arguments together
query GetPerson {
  people(id: "7", avatarSize: LARGE) {
    firstName
    lastName
    avatar
  }
}
```

Here is a sample schema, to be able to respond to this query:

Types:
```yaml
Query:
    type: object
    config:
        fields:
            people:
                type: Person
                resolve: "@=res('person/findOne', [args])"
                args:
                    id: 
                        type: ID!
                    avatarSize:
                        type: String
                        defaultValue: "large"

Person:
    type: object
    config:
        fields:
            firstName: String
            lastName: String
            avatar: String
```
Resolver:
```php
<?php

namespace App\GraphQL\Resolver;

use Overblog\GraphQLBundle\Definition\ArgumentInterface;
use Overblog\GraphQLBundle\Definition\Resolver\AliasedInterface;
use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;

class PersonResolver implements ResolverInterface, AliasedInterface
{
    public static function getAliases(): array
    {
        return [
            'findOneById' => 'person/findOne'
        ];
    }

    public function findOneById(ArgumentInterface $args)
    {
        $personId = $args['id'];
        $avatarSize = $args['avatarSize'];
        
        // ...  
    }
}
```

If you decide to define arguments separately, as you did in your example (this is more complex, but also more flexible), then you have to define another resolver for the `avatar` field (otherwise the argument `size` will simply be ignored):

```yaml
# Root query type
Query:
    type: object
    config:
        fields:
            people:
                type: Person
                resolve: "@=res('person/findOne', [args])"
                args:
                    id: ID!

Person:
    type: object
    config:
        fields:
            # ...
            avatar:
                type: String
                args:
                    size:
                        resolve: "@=res('person/getAvatar', [args])"
                        type: String
                        defaultValue: "large"
```
Resolvers:
```php
<?php

namespace App\GraphQL\Resolver;

use Overblog\GraphQLBundle\Definition\ArgumentInterface;
use Overblog\GraphQLBundle\Definition\Resolver\AliasedInterface;
use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;

class PersonResolver implements ResolverInterface, AliasedInterface
{
    public static function getAliases(): array
    {
        return [
            'findOneById' => 'person/findOne',
            'getAvatar' => 'person/getAvatar'
        ];
    }

    public function findOneById(ArgumentInterface $args)
    {
        $personId = $args['id'];
        # Not available in this resolver
        # $avatarSize = $args['avatarSize'];
        
        // ...  
    }

    public function getAvatar(ArgumentInterface $args)
    {
        $avatarSize = $args["size"];
       
        // ...
    }
}
```

Keep in mind, that in this case the 'avatar' resolver becomes a child of the 'person' resolver: first will be executed `person/findOne`, then 'person/getAvatar'. Data can be passed from parent resolver to child resolvers. To do that, you need to define the special param `value` in the `avatar` resolver:

```yaml
resolve: "@=res('person/getAvatar', [args, value])"
```
```php
public function getAvatar(ArgumentInterface $args, $value)
{
    $avatarSize = $args["size"];

    // This is the value returned by parent resolver
    $value['firstName'],
    $value['lastName']  
    // ...
}
```

You can read more about `args`, `value` and other special params [here](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/expression-language.md#registered-variables)

**Comment by inwaar** [comment]
Hi Timur, thanks for such a detailed reply!

> If you decide to define arguments separately, as you did in your example (this is more complex, but also more flexible), then you have to define another resolver for the avatar field (otherwise the argument size will simply be ignored):

Yes, this is what I was looking for and I really get the arguments in a resolve function.

However I'm also interested in using this with custom scalars.

For example, we have a Date scalar type. Let's say we want to allow clients formatting dates.
I would assume something like:
```yml
Date:
  type: custom-scalar
  config:
    scalarType: '@=newObject("SomeBundle\\Resolver\\ScalarType\\DateType")'
  args:
    format:
      type: "String"
      defaultValue: 'Y-m-d'
```
However this is not working as `args` is not a valid option here.

I guess what can work is still adding resolve options to all the places where we have the `type: Date`
```yml
Invoice:
  type: object
  config:
    fields:
      createDate:
        type: "Date!"
        resolve: "@=resolver('date', [value, args])"
        args:
           format:
           type: "String"
          defaultValue: 'Y-m-d'
      acceptDate:
        type: "Date!"
        resolve: "@=resolver('date', [value, args])"
        args:
           format:
           type: "String"
          defaultValue: 'Y-m-d'
      ...
```
But I do the formatting (and I also want to parse it back) in the scalar type class, so technically what I really want is to get the `args` somehow in the scalar type class.

Maybe I don't fully understand how scalars works in this and the underlying library but I have 2 issues with this:
1) where is supposed the actual formatting to happen for such particular case? in resolve function? what should happen in the scalar type class in this case?
2) it adds too much extra configuration to each property (I guess it can be solved by argument builders) however it seems to me it would be really nice to configure it once per scalar type like this
```yml
Date:
  type: custom-scalar
  config:
    scalarType: '@=newObject("SomeBundle\\Resolver\\ScalarType\\DateType")'
  args:
    format:
      type: "String"
      defaultValue: 'Y-m-d'
```
and then just use it everywhere like
```yml
Invoice:
  type: object
  config:
    fields:
      createDate:
        type: "Date!"
      acceptDate:
        type: "Date!"

User:
  type: object
  config:
    fields:
      createDate:
        type: "Date!"
      lastLoginDate:
        type: "Date!"
```
could it be somehow considered as a feature request?

**Comment by murtukov** [comment]
@inwaar It's not possible to pass arguments to custom scalars, because arguments are meant exclusively for resolvers. Custom scalars are just a serialization/deserealization tool (like Int, String, Float etc) and serialization happens before resolvers are called. Of course technically it would be possible to pass arguments to serialization methods, but it's just not right thing to do.

However there are several ways to solve your problem. 

One of the ways is similar to what you already mentioned above: adding the `resolve` option to all the places where we have the `type: Date`. But instead of using the `resolver` (which is an expression function defined by the bundle), you can register your own expression function, for example `date`:

To register a custom expression function, first you need to create a class, implementing `ExpressionFunction`:
```php
<?php

namespace App\ExpressionLanguage\ExpressionFunction;

use Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction;

class Date extends ExpressionFunction
{
    public function __construct()
    {
        parent::__construct(
            'date',
            function() {
                // This string will be embedded into the resolvers of `createDate` and `acceptDate` fields.
                return '(new \DateTime($value[$info->fieldName]))->format($args[\'format\'])';
            }
        );
    }
}
```
Declare this class as service and add a tag to it:
```yaml
App\ExpressionLanguage\ExpressionFunction\Date:
        tags: [ 'overblog_graphql.expression_function' ]
```
Then you can use this function in any expression:
```yaml
createDate:
    type: "Date!"
    resolve: "@=date()"
        args:
            format:
                type: "String"
                defaultValue: 'Y-m-d'
acceptDate:
    type: "Date!"
    resolve: "@=date()"
        args:
            format:
                type: "String"
                defaultValue: 'Y-m-d'
```
So now it requires a little less typing, but it's still pretty verbose. And this is where the `field builder` comes in handy. Builders just repeat certain parts of your yaml configs. To create a field builder you need first to create a class:
```php
<?php

namespace App\GraphQL\Builder;

use Overblog\GraphQLBundle\Definition\Builder\MappingInterface;

class DateField implements MappingInterface
{
    public function toMappingDefinition(): array
    {
        return [
            'type' => 'String!',
            'resolve' => "@=date()",
            'args' => [
                 'format' => [
                     'type' => 'String', 
                     'defaultValue' => 'Y-m-d'
                 ]
            ]
        ];
    }
}
```
Then you need to register this builder class:
```yaml
overblog_graphql:
    definitions:
        builders:
            field:
                - alias: Date
                  class: App\GraphQL\Builder\DateField
```
Now you can use this builder in your yaml configs:
```yaml
createDate:
    builder: Date
acceptDate:
    builder: Date
```
or even shorter:
```yaml
createDate: { builder: Date }
acceptDate: { builder: Date }
```
This will be automatically transformed (built) into this:
```yaml
createDate:
    type: "Date!"
    resolve: "@=date()"
        args:
            format:
                type: "String"
                defaultValue: 'Y-m-d'
acceptDate:
    type: "Date!"
    resolve: "@=date()"
        args:
            format:
                type: "String"
                defaultValue: 'Y-m-d'
```
You can read about field builders [here](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/builders/field.md).
