### ISSUE TITLE
Backtraces of exceptions thrown in resolvers

### ISSUE THREAD

**Issue by inwaar** [overblog/GraphQLBundle#785]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13.4

Having the following config:
```yml
overblog_graphql:
  ...
  errors_handler:
    map_exceptions_to_parent: true
    exceptions:
      errors:
        - "Throwable"
      warnings:
        - "ProjectNamespace\\WarningException"
```
there is a weird backtrace that doesn't show any traces from a resolve method which makes it almost useless...:
![image](https://user-images.githubusercontent.com/3331076/99884937-30992400-2c3a-11eb-98c9-c21ff7e92e3e.png)

If I comment out `map_exceptions_to_parent` I get the full backtrace but the message `Internal server Error`. 
![image](https://user-images.githubusercontent.com/3331076/99885191-dc8f3f00-2c3b-11eb-9beb-f7a9aa531beb.png)

Is there a way to get the original message as `message` (not `debugMessage`) from any exception and correct backtrace at the same time?
