### ISSUE TITLE
How to define new scalar with .graphql format?

### ISSUE THREAD

**Issue by FedOken** [overblog/GraphQLBundle#820]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | x.y.z

Hi, how to add custom-scalar with `.graphql` format?

From
```
DateTime:
  type: custom-scalar
  config:
    description: "Contain number in seconds"
    serialize: ["App\\GraphQL\\Types\\DateTimeType\\DateTimeType", "serialize"]
    parseValue: ["App\\GraphQL\\Types\\DateTimeType\\DateTimeType", "parseValue"]
    parseLiteral: ["App\\GraphQL\\Types\\DateTimeType\\DateTimeType", "parseLiteral"]
```
to 
`scalar DateTime ...`
