### ISSUE TITLE
SDL first how to prevent invisible types

### ISSUE THREAD

**Issue by koekaverna** [overblog/GraphQLBundle#833]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 1.0.*@dev

Had error: `Runtime Object type "ConreteGroup" is not a possible type for "GroupInterface".`
We use schema first (overblog_graphql.definitions.mappings.types[type: graphql])

I think it's related to https://github.com/webonyx/graphql-php/issues/768
@murtukov Do you have any ideas how to pass invisible types to `Schema`

Configuration is
```yaml
overblog_graphql:
    definitions:
        schema:
            mutation: Mutation
            query: Query
        mappings:
            auto_discover:
                built_in: false
            types:
                -
                    type: graphql
                    dir: '%kernel.project_dir%/api-spec'
                    suffix: null
```

And schema is something like this:
```graph
type Query {
  group(id: ID!): GroupInterface!
}

interface GroupInterface {
  id: ID!
}

type ConreteGroup implements GroupInterface {
  id: ID!
}
```

Any ideas on how to fix it?

**Comment by murtukov** [comment]
Hi @koekaverna 

Just add the `ConcreteGroup` type explicitly to the schema:

```yaml
overblog_graphql:
    definitions:
        schema:
            types: [ConcreteGroup]
# ...
```

This problem happens, because you don't reference the type `ConcreteGroup` directly in other types and the schema builder doesn't load it.
