### ISSUE TITLE
Input-object can't use default values

### ISSUE THREAD

**Issue by Ciloe** [overblog/GraphQLBundle#838]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | dev-master (e42b1e5a524f324126526e73655f87492484a49c)

When I add defaultValue on input-object. I haven't default value in Argument in PHP.

config : 
```yaml
TimeRangeInput:
  type: input-object
  config:
    description: "A time range input."
    fields:
      lower:
        type: "Time"
        description: "The minimum value."
      lowerBound:
        type: "RangeBoundEnum"
        description: "The minimum value bound."
        defaultValue: "("
      upper:
        type: "Time"
        description: "The maximum value."
      upperBound:
        type: "RangeBoundEnum"
        description: "The maximum value bound."
        defaultValue: ")"

AvailabilityInput:
  type: input-object
  config:
    description: "Availability input search."
    fields:
      timeRange:
        type: "TimeRangeInput"
```

Query : 
```gql
query Test {
  availabilities(input: {timeRange: {lower: "10:00", upper: "12:00"}})
}
```

The generated cache file :
```php
<?php

namespace Overblog\GraphQLBundle\__DEFINITIONS__;

use GraphQL\Type\Definition\InputObjectType;
use Overblog\GraphQLBundle\Definition\ConfigProcessor;
use Overblog\GraphQLBundle\Definition\GraphQLServices;
use Overblog\GraphQLBundle\Definition\Type\GeneratedTypeInterface;

/**
 * THIS FILE WAS GENERATED AND SHOULD NOT BE EDITED MANUALLY.
 */
final class TimeRangeInputType extends InputObjectType implements GeneratedTypeInterface
{
    public const NAME = 'TimeRangeInput';
    
    public function __construct(ConfigProcessor $configProcessor, GraphQLServices $services)
    {
        $config = [
            'name' => self::NAME,
            'description' => 'A time range input.',
            'fields' => fn() => [
                'lower' => [
                    'type' => fn() => $services->getType('Time'),
                    'description' => 'The minimum value.',
                ],
                'lowerBound' => [
                    'type' => fn() => $services->getType('RangeBoundEnum'),
                    'description' => 'The minimum value bound.',
                ],
                'upper' => [
                    'type' => fn() => $services->getType('Time'),
                    'description' => 'The maximum value.',
                ],
                'upperBound' => [
                    'type' => fn() => $services->getType('RangeBoundEnum'),
                    'description' => 'The maximum value bound.',
                ],
            ],
        ];
        
        parent::__construct($configProcessor->process($config));
    }
}
```

They are no default values.
