### ISSUE TITLE
Generated type definitions may have namespaces conflicts

### ISSUE THREAD

**Issue by bravik** [overblog/GraphQLBundle#863]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Version/Branch   | 0.13,0.14

I created 2 cusstom validation constraints, with following names:
```php
XXX\V2\Common\Infrastructure\Validator\DatesAreWithinInterval\Constraint
XXX\V2\Common\Infrastructure\Validator\AtLeastOneFieldPresent\Constraint;
```
I usually prefer organizing files by namepsace against naming files like `DatesAreWithinIntervalConstraint`.

And I'm using it for input validation in different files/types:
```yaml
SomeInput:
  type: input-object
  config:
    fields:
      #...
      general:
        type: 'Void'
        validation:
          - XXX\V2\Common\Infrastructure\Validator\AtLeastOneFieldPresent\Constraint: ~
```
I get: an error:
> Compile Error: Cannot use XXX\V2\Common\Infrastructure\Validator\DatesAreWithinInterval\Constraint as Constraint because the name is already in use

Here is one of the generated definition files:
![image](https://user-images.githubusercontent.com/1075618/122146205-f45d3780-ce99-11eb-8144-f7eeef545807.png)

1) Why unused constraints are imported?
2) If there is a namespace collision possible, why not generating a file with FQCN instead of `use` import?
