### ISSUE TITLE
Custom args builder

### ISSUE THREAD

**Issue by benatespina** [overblog/GraphQLBundle#90]
Hi!

Relay root queries does not support more than one argument, at least in Facebook's RelayReact library.

To avoid this limitation I need to wrap the query arguments in other args builder that extends ConnectionArgs adding then my custom arguments. In bundle's documentation this chapter is marked as TODO.

So, is it possible to make a simple example with this topic?

Thank in advance!

**Comment by mcg-web** [comment]
Hi,
 
The relay ArgsBuilder or any other builder, can be combine with custom args. You must just add the args entry as you do when not using builder.

**Comment by benatespina** [comment]
This is my concrete problem:

I'm trying to obtain a Foo collection resource that can be filtered by `customFooArg` and `customFooArg2` but React Relay throws 

```
Uncaught Error: Relay transform error Invalid root field foos; Relay only supports root fields with zero or one argument.
```

```yml
foos:
    type: "FooConnection"
    argsBuilder: ConnectionArgs
    args:
        customFooArg:
            description: "description of custom foo arg"
            type: "String"
        customFooArg2:
            description: "description of custom foo arg 2"
            type: "String"
```

```js
import Relay from 'react-relay';
import RelayQuery from 'react-relay/lib/RelayQuery';
import RelayQueryRequest from 'react-relay/lib/RelayQueryRequest';

const query = Relay.QL`
  query {
    tasks(customFooArg: $customFooArg, customFooArg2: customFooArg2) {
      totalCount,
      edges {
        node {
          id
          description,
          customFooArg,
          customFooArg2
        }
        cursor
      }
      pageInfo {
        endCursor,
        hasNextPage
      }
    }
  }
`;

class FoosQueryRequest extends RelayQueryRequest {
  static build({customFooArg = null, customFooArg2 = null} = {}) {
    return new RelayQueryRequest(
      RelayQuery.Root.create(query, {}, {
        customFooArg,
        customFooArg2
      })
    );
  }
}

export default FoosQueryRequest;
```

**Comment by mcg-web** [comment]
I seems to be a relay limitation, i have try ConnectionArgs builder with one additional arg but never with more... in this [issue ](https://github.com/facebook/relay/issues/94) it look like you must use a input object to bypass limitation.

```yaml
#...
        fields:
            foos:
                 type: "FooConnection"
                 argsBuilder: ConnectionArgs
                 args:
                      customFooArgs:
                            description: "description of custom foo arg"
                            type: "CustomFooArgs"

CustomFooArgs:
    type: input-object
    config:
        fields:
            customFooArg:
                description: "description of custom foo arg"
                type: "String"
            customFooArg2:
                description: "description of custom foo arg 2"
                type: "String"
```
