### ISSUE TITLE
How to use the object value in the access authorization ?

### ISSUE THREAD

**Issue by gregoryalary** [overblog/GraphQLBundle#930]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13

Hello, 👋

Let's say that we have this schema :

```yml
Country:
    type: object
    config:
        description: Pays
        fields:
            id:
                type: "ID!"
            iso:
                type: "String!"
                access: "@=service('schema_right_checker').countryIsInUserScope(???)"
            name:
                type: "String!"
                args:
                    lang:
                        type: "Language!"
            currency:
                type: "Currency!"
```

And this validation logic :

```php
class SchemaRightChecker
{
    public function countryIsInUserScope(Country $country): bool {
        // complex validation based on different field of the $country object
    }
}
```

How can we access the value of  the `Country` is the `countryIsInUserScope` method?
How can we pass it from the expression `access: "@=service('schema_right_checker').countryIsInUserScope(???)"`?

Thanks in advance !
