### ISSUE TITLE
Upload file variable not provided

### ISSUE THREAD

**Issue by adlarge** [overblog/GraphQLBundle#978]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13.6

Hello, i want to upload a file but i always get the error `Variable $file of required type UploadedFile! was not provided.`, whereas the variable is available in Symfony profiler Uploaded Files section.

This what i did, define the UploadedFile type :
```yaml
UploadedFile:
    type: custom-scalar
    config:
        scalarType: '@=newObject("Overblog\\GraphQLBundle\\Upload\\Type\\GraphQLUploadType")'
```
Then define a new mutation :
```yaml
UploadCepc:
  type: "FinalExam"
  resolve: '@=mutation("App\\Infrastructure\\GraphQL\\Mutation\\UploadCepcMutation", [args])'
  args:
      uuid:
          type: "String!"
      file:
          type: "UploadedFile!"
```
This is what i have in the Symfony profiler :
![image](https://user-images.githubusercontent.com/19424497/149175228-b3db436a-9e1f-49fc-9b92-aec5b546401d.png)

Do i miss something ?
