### ISSUE TITLE
Input validation generates wrong Composite validators

### ISSUE THREAD

**Issue by bravik** [overblog/GraphQLBundle#991]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 0.14.2

Validator definition:
```yaml
            validation:
              - AtLeastOneOf:
                  constraints:
                    - Expression: "args['from'] === null && args['to'] !== null"   # Skip if values are null
                    - GreaterThanOrEqual: '-3 months'
                  message: "Specified period is too large. Max 3 month allowed"
                  includeInternalMessages: false
```

In generated type definitions input validation for Symfony `Composite` constraints is now generated in following manner:
```php
  'args' => [
      [
          'name' => 'from',
          'type' => fn() => $services->getType('DateTime'),
          'validation' => fn() => [
              new SymfonyConstraints\AtLeastOneOf([
                  'constraints' => [[
                      'Expression' => 'args[\'from\'] === null && args[\'to\'] !== null',
                  ], [
                      'GreaterThanOrEqual' => '-3 months',
                  ]],
                  'message' => 'Specified period is too large. Max 3 month allowed',
                  'includeInternalMessages' => false,
              ]),
          ],
      ],
```
Which failes with `Array to string conversion`
Which in turn happens when `Composite` attempts to throw it's error:
```
 2 => array:3 [
        "file" => "/app/vendor/symfony/validator/Constraints/Composite.php"
        "line" => 74
        "function" => "sprintf('The value "%s" is not an instance of Constraint in constraint "%s".', array(1), 'Symfony\Component\Validator\Constraints\AtLeastOneOf')"    
      ]
```

In type definition it should be:

```
                    'args' => [
                        [
                            'name' => 'from',
                            'type' => fn() => $services->getType('DateTime'),
                            'validation' => fn() => [
                                new SymfonyConstraints\AtLeastOneOf([
                                     'constraints' => [
                                                    new SymfonyConstraints\Expression(
                                                        'args[\'from\'] === null && args[\'to\'] !== null'
                                                    ),
                                                    new SymfonyConstraints\GreaterThanOrEqual('-3 months')
                                                ],
                                     'message' => 'Specified period is too large. Max 3 month allowed',
                                     'includeInternalMessages' => false,
                                     ]),
                          ],
             ],
```
